import FullCorrectness.Basic
import FullCorrectness.Permutation
import FullCorrectness.Automorphism
import FullCorrectness.Isomorphic
import FullCorrectness.Equivariance

/-!
# Full correctness of the graph canonizer — umbrella + proof plan

Re-exports all submodules under `FullCorrectness/`. External consumers can
`import FullCorrectness` to pull in the whole proof; internal modules import
the specific step(s) they depend on.

The flat-flawed proof in `LeanGraphCanonizerV4Correctness.lean` is retired — its header
explains why its central equivariance claim is literally false. This tree replaces it.

## Target theorem (to be proved in §8)

```
run_canonical : G ≃ H ↔ run (Array.replicate n 0) G = run (Array.replicate n 0) H
```

"`run` with all-zero starting vertex types is a complete graph-isomorphism invariant."

## Status at a glance

| Step | Subject                                           | File                                       | Status          |
| ---- | ------------------------------------------------- | ------------------------------------------ | --------------- |
| §1   | Automorphism group, orbits, `permute` action      | `Basic`, `Permutation`, `Automorphism`     | ✅ proved       |
| §2   | `Isomorphic ↔ ∃σ, H = G.permute σ` bridge         | `Isomorphic`                               | 📋 planned      |
| §3   | Pipeline equivariance under Aut(G) (Stages A–D)   | `Equivariance` (to create)                 | 📋 planned below|
| §4   | `convergeLoop` output is Aut(G)-invariant         | `Equivariance` (to create)                 | 📋 planned below|
| §5   | `breakTie` shrinks typed-automorphism group       | `Tiebreak` (to create)                     | 📋 planned below|
| §6   | Tiebreak choice-independence (conceptual crux)    | `Tiebreak` (to create)                     | 📋 planned below|
| §7   | "Converged types are a prefix of ℕ" invariant     | `Invariants` (to create)                   | 📋 planned below|
| §8   | Assemble `run_canonical`                          | `Main` (to create)                         | 📋 planned below|

--------------------------------------------------------------------------------

## §1  Automorphism group, vertex orbits, and permutation action

**Status: proved.** Definitions and theorems live in `Basic`, `Permutation`, `Automorphism`.

### §1.1  Permutation action on `AdjMatrix` (`Permutation.lean`)

`AdjMatrix.permute σ G` relabels the vertices of `G` by `σ`, using `σ.symm` so that
composition is a left action: `G.permute (σ * τ) = (G.permute τ).permute σ`.

Proved:
- `permute_one`                  — `G.permute 1 = G`
- `permute_mul`                  — left-action composition law
- `permute_permute_symm`         — `(G.permute σ).permute σ⁻¹ = G` (round-trip)
- `permute_symm_permute`         — `(G.permute σ⁻¹).permute σ = G`

### §1.2  Bridge to `swapVertexLabels` (`Permutation.lean`)

`swapVertexLabels_eq_permute : swapVertexLabels v1 v2 G = G.permute (Equiv.swap v1 v2)`

Connects the inductive `Isomorphic` generator to the abstract permutation action.
`Equiv.swap v1 v2` is self-inverse (`toFun = invFun` definitionally), which is why
`.symm` reduces by `rfl` here.

### §1.3  Automorphism subgroup (`Automorphism.lean`)

`AdjMatrix.Aut G : Subgroup (Equiv.Perm (Fin n))` — permutations σ with `G.permute σ = G`.

Proved using `permute_one` / `permute_mul` / `permute_permute_symm` for the three
subgroup axioms. Also `mem_Aut_iff_adj` for the pointwise characterization.

### §1.4–§1.6  Orbits and partition (`Automorphism.lean`)

`AdjMatrix.orbit G v := { w | ∃ σ ∈ Aut G, σ v = w }`

`AdjMatrix.orbitSetoid G : Setoid (Fin n)` packages same-orbit as an equivalence relation
(reflexive via `1 ∈ Aut G`, symmetric via inverses, transitive via composition), so the
orbits partition `Fin n` by Lean's quotient infrastructure.

`orbit_stable_under_Aut` — the forward-facing form: `σ ∈ Aut G → σ v ∈ G.orbit v`.

--------------------------------------------------------------------------------

## §2  Bridge lemma: `Isomorphic ↔ ∃ σ, H = G.permute σ`

**Status: planned.** Stub in `Isomorphic.lean`; detailed plan replicated here.

**Target statements:**
```
theorem Isomorphic_of_permute  {σ} (h : H = G.permute σ) : G ≃ H
theorem permute_of_Isomorphic  (h : G ≃ H) : ∃ σ, H = G.permute σ
theorem Isomorphic_iff_exists_permute : G ≃ H ↔ ∃ σ, H = G.permute σ
```

**Why this matters.** The inductive `Isomorphic` relation is generated by `refl`, `swap`,
and `trans`. Direct induction on it is awkward for the equivariance proofs in §3–§6.
The bridge converts `≃` into a single permutation σ, so all downstream reasoning uses
`Equiv.Perm` and its group operations rather than walking a constructor tree.

**Proof — (⟹) direction.** Induction on `h : G ≃ H`:
- `refl G`: take σ := 1; close by `permute_one`.
- `swap G v1 v2`: take σ := `Equiv.swap v1 v2`; close by `swapVertexLabels_eq_permute`.
- `trans h₁ h₂`: IHs give σ₁ with `G₂ = G₁.permute σ₁` and σ₂ with `G₃ = G₂.permute σ₂`.
  Take σ := **σ₂ * σ₁** (order forced by the left-action: `permute_mul` says
  `G.permute (σ₂ * σ₁) = (G.permute σ₁).permute σ₂`).

**Proof — (⟸) direction.** Given `H = G.permute σ`, show `G ≃ H` by induction on a
transposition decomposition of σ via Mathlib's `Equiv.Perm.swap_induction_on`.
Define `P σ := G ≃ G.permute σ`:
- `P 1`: `G ≃ G.permute 1 = G` by `Isomorphic.refl` + `permute_one`.
- `P (Equiv.swap x y * f)` from `P f`: by `permute_mul`,
  `G.permute (swap x y * f) = (G.permute f).permute (swap x y)
   = swapVertexLabels x y (G.permute f)` (by `swapVertexLabels_eq_permute`);
  use `Isomorphic.swap` then `Isomorphic.trans` with the IH.

**Risk R1.** `Equiv.Perm.swap_induction_on` may differ in name on the pinned toolchain;
fallback is induction on `σ.support` size.

**Risk R2.** Composition order (σ₂ * σ₁, not σ₁ * σ₂) must match `permute_mul`
consistently throughout.

--------------------------------------------------------------------------------

## §3  Pipeline equivariance under Aut(G)

**Goal.** For any σ ∈ `Aut G` and any vertex-type array `vts`, the canonizer pipeline
applied to the σ-permuted graph with σ-permuted types produces the σ-permuted output.

Crucially this is quantified over `σ ∈ Aut G`, **not** all of `Sym(Fin n)`. The old flat
proof quantified over all of `Sym(Fin n)`, which is false because `breakTie` is not
equivariant under arbitrary label permutations (only under automorphisms).

**Stage A — `initializePaths`.**
```
σ ∈ Aut G  →  paths in `swapVL-via-σ G` at (d, s, e)
              correspond to paths in G at (d, σ⁻¹ s, σ⁻¹ e)
```
with edge types, vertex indices, and nested `PathSegment` structures all relabeled by σ.
Proof by induction on depth; the action on `PathSegment`/`PathsBetween`/`PathsFrom` lifts
componentwise from the Fin-level action.

**Stage B — `calculatePathRankings`.** If the input `PathState` and `vertexTypes` are
σ-related, then the output ranks satisfy
```
ranks'.betweenRanks[d][s][e] = ranks.betweenRanks[d][σ⁻¹ s][σ⁻¹ e],
ranks'.fromRanks[d][s]       = ranks.fromRanks[d][σ⁻¹ s].
```
Proof by induction on depth, using that `comparePathSegments` / `comparePathsBetween` /
`comparePathsFrom` only depend on σ-invariant features (edge types and endpoint vertex
types are preserved because σ ∈ Aut G; the recursive rank references are equivariant by IH).

**Stage C — `orderVertices`.** `convergeOnce` reads `fromRanks` (equivariant by Stage B),
so it preserves the relation. `breakTie` is the interesting case — it is equivariant under
`Aut(G)` (not under `Sym(Fin n)`) *at each outer-loop iteration*, because the vertices it
chooses between are all in the same Aut(G)-orbit. See §6 for why the *choice* of which
tied vertex to promote doesn't affect the final answer.

**Stage D — `labelEdgesAccordingToRankings`.** With distinct ranks (§7), the vertex at
position p in the σ-permuted sort is σ applied to the vertex at position p in the original.
The edge at (p, q) is then `(σ·G).adj(σwₚ)(σwₙ) = G.adj wₚ wₙ` by the Aut(G) property.

**Deliverable.** Four equivariance theorems in `FullCorrectness/Equivariance.lean`:
```
initializePaths_Aut_equivariant      : σ ∈ Aut G → ...  (Stage A)
calculatePathRankings_Aut_equivariant: σ ∈ Aut G → ...  (Stage B)
orderVertices_Aut_equivariant        : σ ∈ Aut G → ...  (Stage C, modulo §6)
labelEdges_Aut_equivariant           : σ ∈ Aut G → ...  (Stage D, given §7)
```

## §4  `convergeLoop` output is Aut(G)-invariant

**Goal.**
```
σ ∈ Aut G  ∧  (∀ v, vts[σ v] = vts[v])  →  ∀ v, (convergeLoop state vts fuel)[σ v]
                                                  = (convergeLoop state vts fuel)[v]
```
i.e. if the input vertex types are Aut(G)-invariant, so is the output.

**Why.** `convergeOnce` writes `rankState.getFrom (n-1) v` into slot `v`. That value
depends only on paths-from-v; any σ ∈ Aut G bijects paths-from-v with paths-from-(σv)
preserving edge types and endpoint types (the endpoint types are Aut-invariant by the IH
on vertex-types). So the multisets fed into `comparePathsFrom` are identical, the ranks
are identical, and Aut-invariance is preserved. Induct on the fuel parameter.

**Corollary.** Starting from the all-zeros array (which is trivially Aut-invariant), after
`convergeLoop`, vertices in the same Aut(G)-orbit carry the same type.

**Deliverable.** One theorem in `FullCorrectness/Equivariance.lean`:
```
convergeLoop_Aut_invariant : σ ∈ Aut G → vts σ-invariant → convergeLoop output σ-invariant
```

## §5  `breakTie` shrinks the typed-automorphism group

Let `Aut(G, T)` := `{ σ ∈ Aut G | σ permutes T as a bijection on equal values }` be the
automorphisms preserving a given typing T. This is a subgroup of `Aut G`.

**Goal.** Let T be Aut(G)-invariant, let t₀ be the smallest value held by at least two
vertices, let V_{t₀} be its type-class, let v* := min V_{t₀} (by Fin order), and let
T' := `breakTie T t₀` (which promotes every vertex in V_{t₀} except v*). Then
```
Aut(G, T')  =  { σ ∈ Aut(G, T) | σ v* = v* }                         (stabilizer of v*)
```

**Why.** σ ∈ Aut(G, T') iff σ preserves T' iff σ sends the unique type-t₀ vertex (v*) to
itself and sends V_{t₀} \ {v*} to itself. The first condition forces σ v* = v*; the second
is then automatic given σ ∈ Aut(G, T).

**Strict shrinking.** If |V_{t₀}| ≥ 2, then v* is not Aut(G, T)-fixed (all elements of V_{t₀}
are in the same Aut(G, T)-orbit by §4's corollary, and there are ≥ 2 of them), so the
stabilizer is a proper subgroup. After each tiebreak, the typed-automorphism group strictly
shrinks; after at most n tiebreaks it is trivial (all types distinct).

**Deliverable.** Two theorems in `FullCorrectness/Tiebreak.lean`:
```
breakTie_Aut_stabilizer   : Aut(G, breakTie T t₀) = stab_{Aut(G,T)}(min V_{t₀})
breakTie_strict_shrink    : |V_{t₀}| ≥ 2 → Aut(G, breakTie T t₀) ⊊ Aut(G, T)
```

## §6  Tiebreak choice-independence (the conceptual crux)

This is the step the old flat proof did not need — because it assumed `breakTie` never
fires — and the reason the flat proof fails once tiebreaks are real.

**Goal.** Let T be Aut(G)-invariant. Let t₀ be the smallest repeated value, and let v₁, v₂
be any two vertices in V_{t₀} (so by §4 they are in the same Aut(G, T)-orbit). Let T₁ / T₂
be the result of promoting v₁ / v₂ respectively. Then
```
 Run the remainder of the canonizer pipeline (including all subsequent tiebreaks and the
 final relabel) starting from (G, T₁) vs. (G, T₂). The **final canonical matrices are equal.**
```

**Why.** Let τ ∈ Aut(G, T) with τ v₁ = v₂ (exists by same-orbit). Then the pair (G, T₂)
equals τ · (G, T₁) in the sense that G is τ-invariant (τ ∈ Aut G) and T₂ = τ · T₁ (the
promoted-type array, permuted by τ, matches the other choice). By Aut(G)-equivariance of
the remaining pipeline (§3), running on τ · (G, T₁) produces τ · (final output). But the
final output has all types distinct, so the relabel step in §8 sorts τ away, producing the
same canonical matrix.

Formally this is proved by **strong induction on |Aut(G, T)|**:

  Base: `|Aut(G, T)| = 1` → T has all types distinct → no more tiebreaks → relabel is
        deterministic, result is independent of all upstream choices.

  Step: `|Aut(G, T)| > 1` → by §5, next tiebreak further shrinks the group. Any two choices
        of promoted representative are in the same Aut(G, T)-orbit, so the promoted-type
        arrays are τ-related. Apply §3 equivariance + IH.

**Deliverable.** One theorem in `FullCorrectness/Tiebreak.lean`:
```
tiebreak_choice_independent : ∀ (two τ-related states), same final canonical output
```

## §7  "Converged types are a prefix of ℕ" invariant

`orderVertices` calls `breakTie convergedTypes (Int.ofNat targetPosition)` where
`targetPosition` is the outer-loop counter `0, 1, …, n-1`, NOT the smallest tied value.
For §5/§6 to apply, we need: at iteration p, the smallest tied value is exactly p.

**Goal.**
```
∀ p ≤ n, after p outer iterations, the typing takes values exactly in {0, 1, …, p-1, k}
         where k is either the next tied value (= p, if one exists) or n (if all distinct).
```

**Why.** Initial types from `convergeLoop` form a prefix-of-ℕ ranking (this follows from
`assignRanks`, which assigns the index of the first element in each equivalence class;
after dense-rank normalization, values are exactly 0..m-1 for some m ≤ n). Each `breakTie`
with target p leaves values 0..p-1 unchanged and promotes some value-p vertices to p+1
(which may then be re-dense-ranked by the next `convergeLoop` call — verify this claim is
preserved by `convergeLoop` on a prefix typing).

**Deliverable.** One invariant theorem in `FullCorrectness/Invariants.lean`:
```
orderVertices_prefix_invariant : ∀ p < n, after p iterations, types ⊆ Fin (p+1)  (or similar)
```

**Watch-out.** If the algorithm's rank assignment is not dense (e.g. skips values), this
invariant fails, and the whole argument unravels. Check `assignRanks` + `computeDenseRanks`
carefully.

## §8  Assembling `run_canonical`

With §1–§7 in hand:

**(→)** Given G ≃ H. By §2, there is σ : Equiv.Perm (Fin n) with H = G.permute σ. We want
`run 0 H = run 0 G`. Decompose the pipeline:

  1. `initializePaths` + `convergeLoop` + all iterations of `breakTie`/`convergeLoop` →
     some final typing T_G (for G) / T_H (for H).
  2. `labelEdgesAccordingToRankings T_G G` / `labelEdgesAccordingToRankings T_H H`.

The pipeline applied to H = G.permute σ with the all-zeros input is related by σ to the
pipeline applied to G. For the part of σ inside Aut G, this is §3 + §4 equivariance (T_H
is σ·T_G up to tiebreak choices, and §6 says those don't matter). For the part of σ outside
Aut G… there is no "outside" — σ takes G to G.permute σ = H, and H ≃ G, so this is just
restating that G, H are isomorphic. The canonical output depends on the abstract graph,
not the labeling.

**(←)** Given `run 0 G = run 0 H`. By `run_isomorphic_to_input` (proved in §4 of the flat
file, reused here), G ≃ run 0 G and H ≃ run 0 H. Chain:
```
G ≃ run 0 G = run 0 H ≃⁻¹ H   ⟹   G ≃ H.
```
This direction re-uses the genuinely-proved §4 lemma from the old flat file.

**Deliverable.** The capstone theorem in `FullCorrectness/Main.lean`:
```
theorem run_canonical : G ≃ H ↔ run (Array.replicate n 0) G = run (Array.replicate n 0) H
```

--------------------------------------------------------------------------------

## Risks and open invariants

**R1.** §6 strong induction requires `|Aut(G, T)|` to be a well-founded measure. Trivial
with `Fintype`, but we need to actually put a `Fintype` instance on `Aut(G, T)` (it is a
subgroup of `Sym(Fin n)` which is finite).

**R2.** §7's prefix-of-ℕ invariant assumes dense ranking throughout. Verify in
`assignRanks` and `computeDenseRanks` that values are always exactly 0..m-1.

**R3.** `convergeLoop` is given fuel equal to `state.vertexCount`. Correctness does not
require it to actually reach a fixed point — §4 says the output is always Aut-invariant,
fixed point or not — but we should double-check that "output is Aut-invariant at every
iteration" is what induction gives us, not the weaker "fixed point is Aut-invariant."

**R4.** §2's (⟸) direction uses Mathlib's `Equiv.Perm.swap_induction_on`; the exact name
on the pinned toolchain (`leanprover/lean4:v4.30.0-rc2` + Mathlib master) needs to be
confirmed. Fallback: induct on `σ.support` size.

**R5.** `Fin`/`Nat` bounds on `set!`, `getD`, and the array-index arithmetic throughout
will produce side conditions. Collect into a single `def` + lemmas file if they multiply.

## Suggested development order

Serial dependencies run §1 → §2 → §3 → §4 → (§5 ∥ §7) → §6 → §8. The independent
work (Mathlib-facing infrastructure: §1 done; §2 is mostly Mathlib-plumbing) can proceed
in parallel with algorithm-facing work (§3–§5 are about the specific data structures of
this canonizer).

§6 is the single hardest step and should be the budgeting focus once §3–§5 are in place.
-/
