name = "GraphCanonizationProofs"
version = "0.0.1"
defaultTargets = ["GraphCanonizationProofs"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#master"

[[lean_lib]]
name = "LeanGraphCanonizerV4"

[[lean_lib]]
name = "UniqueGraphsBySize"

[[lean_lib]]
name = "LeanGraphCanonizerV4Tests"
