open Nat

namespace Graph

abbrev VertexType := Nat
abbrev EdgeType   := Nat

/-! ## Adjacency matrix -/

structure AdjMatrix (vertexCount : Nat) where
  adj : Fin vertexCount → Fin vertexCount → EdgeType

namespace AdjMatrix

variable {vertexCount : Nat}

def swapVertexLabels (vertex1 vertex2 : Fin vertexCount) (G : AdjMatrix vertexCount) : AdjMatrix vertexCount :=
  { adj := fun fromVertex toVertex =>
      let mappedFrom := if fromVertex = vertex1 then vertex2 else if fromVertex = vertex2 then vertex1 else fromVertex
      let mappedTo   := if toVertex   = vertex1 then vertex2 else if toVertex   = vertex2 then vertex1 else toVertex
      G.adj mappedFrom mappedTo }

/--
Inductive graph isomorphism between adjacency matrices, generated by reflexivity,
vertex-label swaps, and transitivity. Two matrices are `Isomorphic` iff one can be
obtained from the other by a finite sequence of vertex relabelings.
-/
inductive Isomorphic : AdjMatrix vertexCount → AdjMatrix vertexCount → Prop
  | refl  (G : AdjMatrix vertexCount)                                       : Isomorphic G G
  | swap  (G : AdjMatrix vertexCount) (vertex1 vertex2 : Fin vertexCount)   : Isomorphic G (swapVertexLabels vertex1 vertex2 G)
  | trans {G₁ G₂ G₃ : AdjMatrix vertexCount}
      : Isomorphic G₁ G₂ → Isomorphic G₂ G₃ → Isomorphic G₁ G₃

@[inherit_doc] scoped infixl:50 " ≃ " => Isomorphic

def adjToString (G : AdjMatrix vertexCount) : String :=
  let rowIndices := List.finRange vertexCount
  let rowStrings := rowIndices.map fun rowIdx =>
    let colValues := (List.finRange vertexCount).map fun colIdx => toString (G.adj rowIdx colIdx)
    String.join (colValues.intersperse " ")
  String.join (rowStrings.intersperse "\n")

instance : ToString (AdjMatrix vertexCount) := ⟨adjToString⟩

end AdjMatrix

/-! ## Path structures

The path data structures are parametrized by `vertexCount` and use `Fin vertexCount` for
all vertex slots. This makes the equivariance proofs in `FullCorrectness/` directly
applicable: `Equiv.Perm (Fin vertexCount)` acts on the structures by mapping indices
through `σ` without any `Nat`-bounds bookkeeping. The `subDepth` field of `PathSegment.inner`
is kept as `Nat` because it is a depth index (0..vertexCount-1) that the algorithm
manipulates with `depthFin.val - 1`; constraining it to `Fin vertexCount` adds little. -/

inductive PathSegment (vertexCount : Nat) where
  | bottom (vertexIndex : Fin vertexCount)                                                                    : PathSegment vertexCount
  -- subDepth/subStart/subEnd index into betweenRanks; in C# this is an AllPathsBetween object reference
  | inner  (edgeType : EdgeType) (subDepth : Nat) (subStart subEnd : Fin vertexCount)                         : PathSegment vertexCount
deriving Repr, BEq

structure PathsBetween (vertexCount : Nat) where
  depth            : Nat
  startVertexIndex : Fin vertexCount
  endVertexIndex   : Fin vertexCount
  connectedSubPaths : List (PathSegment vertexCount)
deriving Repr

structure PathsFrom (vertexCount : Nat) where
  depth            : Nat
  startVertexIndex : Fin vertexCount
  pathsToVertex    : List (PathsBetween vertexCount)
deriving Repr

structure PathState (vertexCount : Nat) where
  pathsOfLength : Array (Array (PathsFrom vertexCount))

structure RankState where
  betweenRanks : Array (Array (Array Nat))
  fromRanks    : Array (Array Nat)

def RankState.getBetween (rankState : RankState) (depth startIdx endIdx : Nat) : Nat :=
  ((rankState.betweenRanks.getD depth #[]).getD startIdx #[]).getD endIdx 0

def RankState.getFrom (rankState : RankState) (depth startIdx : Nat) : Nat :=
  (rankState.fromRanks.getD depth #[]).getD startIdx 0

/-! ## Helpers -/

def insertSorted {α : Type} (cmp : α → α → Ordering) (newItem : α) : List α → List α
  | []               => [newItem]
  | listHead :: listTail => if cmp newItem listHead != .gt then newItem :: listHead :: listTail else listHead :: insertSorted cmp newItem listTail

def sortBy {α : Type} (cmp : α → α → Ordering) : List α → List α
  | []          => []
  | head :: rest => insertSorted cmp head (sortBy cmp rest)

def orderInsensitiveListCmp {α : Type} (cmp : α → α → Ordering) (list1 list2 : List α) : Ordering :=
  if list1.length != list2.length then
    if list1.length < list2.length then .gt else .lt
  else
    (sortBy cmp list1).zip (sortBy cmp list2) |>.foldl
      (fun currentOrder (elemA, elemB) => if currentOrder != .eq then currentOrder else cmp elemA elemB) .eq

/-! ## Comparison functions -/

def comparePathSegments {vertexCount : Nat}
    (vertexTypes  : Array VertexType)
    (betweenRanks : Nat → Nat → Nat → Nat)
    : PathSegment vertexCount → PathSegment vertexCount → Ordering
  | .bottom xVertexIdx,              .bottom yVertexIdx              =>
      compare (vertexTypes.getD xVertexIdx.val 0) (vertexTypes.getD yVertexIdx.val 0)
  | .inner xEdge xDepth xStart xEnd, .inner yEdge yDepth yStart yEnd =>
      let xRank := betweenRanks xDepth xStart.val xEnd.val
      let yRank := betweenRanks yDepth yStart.val yEnd.val
      if xRank != yRank then compare yRank xRank
      else if xEdge != yEdge then compare yEdge xEdge
      else .eq
  | _, _ => panic! "Cannot compare bottom and inner PathSegments"

def comparePathsBetween {vertexCount : Nat}
    (vertexTypes  : Array VertexType)
    (betweenRanks : Nat → Nat → Nat → Nat)
    (pathX pathY : PathsBetween vertexCount) : Ordering :=
  let xEndType := vertexTypes.getD pathX.endVertexIndex.val 0
  let yEndType := vertexTypes.getD pathY.endVertexIndex.val 0
  if xEndType != yEndType then compare xEndType yEndType
  else orderInsensitiveListCmp (comparePathSegments vertexTypes betweenRanks)
         pathX.connectedSubPaths pathY.connectedSubPaths

def comparePathsFrom {vertexCount : Nat}
    (vertexTypes  : Array VertexType)
    (betweenRanks : Nat → Nat → Nat → Nat)
    (pathX pathY : PathsFrom vertexCount) : Ordering :=
  let xStartType := vertexTypes.getD pathX.startVertexIndex.val 0
  let yStartType := vertexTypes.getD pathY.startVertexIndex.val 0
  if xStartType != yStartType then compare xStartType yStartType
  else orderInsensitiveListCmp (comparePathsBetween vertexTypes betweenRanks)
         pathX.pathsToVertex pathY.pathsToVertex

/-! ## Path initialization -/

def initializePaths {vertexCount : Nat} (G : AdjMatrix vertexCount) : PathState vertexCount :=
  let vertices := List.finRange vertexCount
  { pathsOfLength := vertices.toArray.map fun depthFin =>
      vertices.toArray.map fun startFin =>
        { depth            := depthFin.val
          startVertexIndex := startFin
          pathsToVertex    :=
            vertices.map fun endFin =>
              { depth            := depthFin.val
                startVertexIndex := startFin
                endVertexIndex   := endFin
                connectedSubPaths :=
                  if depthFin.val = 0 then
                    if startFin = endFin then [.bottom startFin] else []
                  else
                    vertices.map fun midFin =>
                      .inner (G.adj midFin endFin) (depthFin.val - 1) startFin midFin } } }

/-! ## Ranking

`assignRanks` produces **dense** ranks: each equivalence class gets a unique consecutive
ordinal `0, 1, 2, …`. For example, sorted `[a, a, b, c]` ↦ `[(a,0), (a,0), (b,1), (c,2)]`.
[sparse→dense] Was previously sparse (`[(a,0), (a,0), (b,2), (c,3)]`), where rank = first
index of the class. The dense form is what `breakTie` (below) needs to maintain a clean
prefix-of-ℕ invariant on the typing array. -/

def assignRanks {α : Type} (cmp : α → α → Ordering) (sorted : List α)
    : List (α × Nat) :=
  let (reversedList, _) := sorted.foldl
    (fun (pair : List (α × Nat) × Option (α × Nat)) item =>
      let (revList, lastEntry) := pair
      let rank : Nat :=
        match lastEntry with
        | none                      => 0
        | some (prevItem, prevRank) => if cmp prevItem item == .eq then prevRank else prevRank + 1
      ((item, rank) :: revList, some (item, rank)))
    (([] : List (α × Nat)), none)
  reversedList.reverse

def setBetween (betweenTable : Array (Array (Array Nat)))
    (depth startIdx endIdx : Nat) (rank : Nat) : Array (Array (Array Nat)) :=
  let depthSlice := betweenTable.getD depth #[]
  let startSlice := depthSlice.getD startIdx #[]
  betweenTable.set! depth (depthSlice.set! startIdx (startSlice.set! endIdx rank))

def calculatePathRankings {vertexCount : Nat} (state : PathState vertexCount) (vertexTypes : Array VertexType) : RankState :=
  let numVertices := vertexCount
  let emptyBetweenTable : Array (Array (Array Nat)) :=
    (Array.range numVertices).map fun _ => (Array.range numVertices).map fun _ => (Array.range numVertices).map fun _ => (0 : Nat)
  let emptyFromTable : Array (Array Nat) :=
    (Array.range numVertices).map fun _ => (Array.range numVertices).map fun _ => (0 : Nat)
  let (finalBetween, finalFrom) := (List.range numVertices).foldl
    (fun (accumulated : Array (Array (Array Nat)) × Array (Array Nat)) depth =>
      let (currentBetween, currentFrom) := accumulated
      let pathsAtDepth  := (state.pathsOfLength.getD depth #[]).toList
      let allBetween    := pathsAtDepth.foldl (fun collectedPaths pathsFrom => collectedPaths ++ pathsFrom.pathsToVertex) []
      let betweenRankFn : Nat → Nat → Nat → Nat := fun rankDepth rankStart rankEnd =>
        ((currentBetween.getD rankDepth #[]).getD rankStart #[]).getD rankEnd 0
      let compareBetween  := comparePathsBetween vertexTypes betweenRankFn
      let updatedBetween  := (assignRanks compareBetween (sortBy compareBetween allBetween)).foldl
                              (fun (betweenAcc : Array (Array (Array Nat))) item =>
                                let (pathBetween, rank) := item
                                setBetween betweenAcc depth pathBetween.startVertexIndex.val pathBetween.endVertexIndex.val rank)
                              currentBetween
      let updatedBetweenFn : Nat → Nat → Nat → Nat := fun rankDepth rankStart rankEnd =>
        ((updatedBetween.getD rankDepth #[]).getD rankStart #[]).getD rankEnd 0
      let compareFrom     := comparePathsFrom vertexTypes updatedBetweenFn
      let updatedFrom     := (assignRanks compareFrom (sortBy compareFrom pathsAtDepth)).foldl
                              (fun (fromAcc : Array (Array Nat)) item =>
                                let (pathFrom, rank) := item
                                let depthSlice := fromAcc.getD depth #[]
                                fromAcc.set! depth (depthSlice.set! pathFrom.startVertexIndex.val rank))
                              currentFrom
      (updatedBetween, updatedFrom))
    (emptyBetweenTable, emptyFromTable)
  { betweenRanks := finalBetween, fromRanks := finalFrom }

/-! ## Vertex ordering -/

def convergeOnce {vertexCount : Nat} (state : PathState vertexCount) (vertexTypes : Array VertexType)
    : Array VertexType × Bool :=
  let rankState   := calculatePathRankings state vertexTypes
  let numVertices := vertexCount
  (List.range numVertices).foldl
    (fun (pair : Array VertexType × Bool) vertexIdx =>
      let (typeArray, changed) := pair
      let newRank := rankState.getFrom (numVertices - 1) vertexIdx
      if newRank != typeArray.getD vertexIdx 0 then (typeArray.set! vertexIdx newRank, true)
      else (typeArray, changed))
    (vertexTypes, false)

--This function provides a partial ordering of vertices, ordering every vertex into types, where each type shares a symmetry between them (and implicitly automorphic)
def convergeLoop {vertexCount : Nat} (state : PathState vertexCount) (vertexTypes : Array VertexType) : Nat → Array VertexType
  | 0        => vertexTypes
  | fuel + 1 =>
    let (updatedTypes, changed) := convergeOnce state vertexTypes
    if changed then convergeLoop state updatedTypes fuel else updatedTypes

/-! ### `breakTie`

`breakTie vts target` collapses one symmetry by promoting all-but-one of the vertices in
the value-`target` class to value `target + 1`. To remain compatible with **dense** input
typings (where `target + 1` is the next class's value), it first opens a one-slot gap by
shifting every value `> target` up by one. After the shift, value `target + 1` is empty,
and the promotion fills it with the (k − 1) promoted vertices.

[sparse→dense] Originally `breakTie` was a single fold over the input array that promoted
in-place. That worked only because **sparse** ranks left a gap of size `≥ k` after every
class of size `k`, so promoting to `target + 1` could not collide with the next class. With
dense ranks the gap is gone, hence the `shiftAbove` pre-pass.

The whole operation is gated on `count ≥ 2`: when there is no tie to break, we leave `vts`
untouched. Shifting unconditionally would create a spurious gap and break the dense-prefix
invariant maintained by the outer loop. -/

/-- Shift every value strictly greater than `target` up by 1, opening a gap at `target + 1`. -/
def shiftAbove (target : VertexType) (vts : Array VertexType) : Array VertexType :=
  vts.map (fun v => if v > target then v + 1 else v)

/-- The promote stage of `breakTie`: keep the first vertex with value `target` at `target`
and bump every other such vertex to `target + 1`. Assumes there is no existing `target + 1`
class to collide with (caller's responsibility — the outer `breakTie` ensures this via
`shiftAbove`). -/
def breakTiePromote (vertexTypes : Array VertexType) (target : VertexType) : Array VertexType × Bool :=
  let result := (List.range vertexTypes.size).foldl
    (fun (triple : Array VertexType × Bool × Bool) vertexIdx =>
      let (typeArray, firstAppearance, changed) := triple
      if typeArray.getD vertexIdx 0 == target then
        if firstAppearance then (typeArray, false, changed)
        else (typeArray.set! vertexIdx (target + 1), false, true)
      else (typeArray, firstAppearance, changed))
    (vertexTypes, true, false)
  let (typeArray, _, changed) := result
  (typeArray, changed)

/-- Top-level tiebreak: if at least two vertices share value `target`, open a gap above
`target` (`shiftAbove`) and then promote all-but-one to `target + 1`. Otherwise return
`vts` unchanged. The gating preserves dense typings as input/output. -/
def breakTie (vertexTypes : Array VertexType) (target : VertexType) : Array VertexType × Bool :=
  let count := vertexTypes.foldl (fun c v => if v == target then c + 1 else c) 0
  if count < 2 then (vertexTypes, false)
  else breakTiePromote (shiftAbove target vertexTypes) target

def orderVertices {vertexCount : Nat} (state : PathState vertexCount) (vertexTypes : Array VertexType) : Array VertexType :=
  (List.range vertexCount).foldl
    (fun currentTypes targetPosition =>
      let convergedTypes := convergeLoop state currentTypes vertexCount
      (breakTie convergedTypes targetPosition).1)
    vertexTypes

/-! ## Edge labeling -/

/-- Assign a unique position in `[0, numVertices)` to each vertex, using `vertexRankings`
as the primary key and the vertex index as a tiebreaker. The result is a permutation:
`output[v] = position of v in the sort by (vertexRankings[v], v)`. Used by
`labelEdgesAccordingToRankings` to map vertices to their canonical positions when ranks
are guaranteed all-distinct (the post-`orderVertices` invariant from §7).

Note: this is **not** a "dense rank" in the rank-statistics sense — it does not assign
equal output values to ties. It assumes ties have already been broken by §7. The name
is preserved for backward compatibility; see `getArrayRank` below for the proper dense
ranking that we use as the entry-point normalization. -/
def computeDenseRanks (numVertices : Nat) (vertexRankings : Array VertexType) : Array Nat :=
  let pairs : List (VertexType × Nat) := (List.range numVertices).map fun vertexIdx => (vertexRankings.getD vertexIdx 0, vertexIdx)
  let cmp : (VertexType × Nat) → (VertexType × Nat) → Ordering :=
    fun pair1 pair2 => if pair1.1 != pair2.1 then compare pair1.1 pair2.1 else compare pair1.2 pair2.2
  let sorted := sortBy cmp pairs
  (List.range sorted.length).foldl
    (fun (positionArray : Array Nat) sortedIdx => positionArray.set! (sorted.getD sortedIdx (0, 0)).2 sortedIdx)
    ((Array.range numVertices).map fun _ => 0)

/-- True dense rank of each entry: replaces each value in `arr` by the number of distinct
values strictly less than it. Ties are preserved. For example,
`[5, 0, 5, 3]` ↦ `[2, 0, 2, 1]` (values `0 < 3 < 5`).

[sparse→dense] Was previously "count of strictly smaller values" (sparse-style — for the
example, gave `[3, 0, 3, 1]`). Both forms preserve the partition and the order, so
downstream comparisons are unaffected; the dense form keeps the `IsPrefixTyping` invariant
true at the entry point of `run`. -/
def getArrayRank (arr : Array VertexType) : Array VertexType :=
  let pairs : List (VertexType × Nat) :=
    (List.range arr.size).map fun i => (arr.getD i 0, i)
  let sorted := sortBy (fun (a b : VertexType × Nat) => compare a.1 b.1) pairs
  let (assignmentsRev, _) := sorted.foldl
    (fun (acc : List (Nat × Nat) × Option (VertexType × Nat))
         (item : VertexType × Nat) =>
      let (revList, last) := acc
      let rank : Nat := match last with
        | none                       => 0
        | some (lastVal, lastRank)   => if lastVal == item.1 then lastRank else lastRank + 1
      ((item.2, rank) :: revList, some (item.1, rank)))
    (([] : List (Nat × Nat)), none)
  assignmentsRev.foldl
    (fun (out : Array VertexType) (entry : Nat × Nat) => out.set! entry.1 entry.2)
    (Array.replicate arr.size 0)

def labelEdgesAccordingToRankings {vertexCount : Nat}
    (vertexRankings : Array VertexType) (G : AdjMatrix vertexCount) : AdjMatrix vertexCount :=
  let vertices     := List.finRange vertexCount
  let denseRankings := computeDenseRanks vertexCount vertexRankings
  (vertices.foldl
    (fun (accumulated : AdjMatrix vertexCount × Array Nat) currentFin =>
      let (graph, rankMap) := accumulated
      let targetPos := currentFin.val
      match vertices.find? (fun searchFin => rankMap.getD searchFin.val 0 == targetPos) with
      | none          => (graph, rankMap)
      | some sourceFin =>
        let sourceIdx    := sourceFin.val
        let swappedGraph := graph.swapVertexLabels currentFin sourceFin
        let rankAtSource := rankMap.getD sourceIdx 0
        let rankAtTarget := rankMap.getD targetPos 0
        (swappedGraph, (rankMap.set! sourceIdx rankAtTarget).set! targetPos rankAtSource))
    (G, denseRankings)).1

/-! ## Entry point -/

def run {vertexCount : Nat} (vertexTypes : Array VertexType) (G : AdjMatrix vertexCount) : AdjMatrix vertexCount :=
  let vertexRanks  := getArrayRank vertexTypes
  let state        := initializePaths G
  let orderedRanks := orderVertices state vertexRanks
  labelEdgesAccordingToRankings orderedRanks G

end Graph
