import LeanGraphCanonizerV4
import Mathlib.Tactic

/-!
# Correctness of the Full Graph Canonizer (with tiebreak + refinement)

The existing `LeanGraphCanonizerV4Correctness.lean` file proves correctness under the
simplifying assumption that `breakTie` is never invoked — i.e. that `convergeLoop` alone
separates every orbit. That assumption fails on graphs with non-trivial automorphism groups
(e.g. C₄, K_{3,3}, any vertex-transitive graph). This file sketches, in comments, what a
proof of correctness of the *full* algorithm — convergence, tiebreak, refinement, repeat —
should look like, and what auxiliary results it would require.

--------------------------------------------------------------------------------
## 1. Statement of the theorem

We want the same headline result as the simplified version:

  `run_canonical : G ≃ H ↔ run (Array.replicate n 0) G = run (Array.replicate n 0) H`

Two directions:

  (→) Isomorphic graphs canonize to the *same* adjacency matrix.
  (←) If canonizations agree, a sequence of label swaps witnesses G ≃ H.

The (←) direction is unaffected by tiebreaking: it only needs that `run zeros G ≃ G`,
which holds because `labelEdgesAccordingToRankings` is a composition of `swapVertexLabels`.
The interesting direction is (→), and it is where the previous proof broke.

--------------------------------------------------------------------------------
## 2. Why the old proof failed once tiebreaks are real

The old proof's key step was **equivariance**: for any permutation σ : Fin n ≃ Fin n,

    run σ·vertexTypes (σ·G) = σ · (run vertexTypes G)

where σ acts on an `AdjMatrix` by relabeling and on a type-array by permuting indices.
Then for the all-zeros input, σ·zeros = zeros, so the two outputs are literally equal.

`breakTie` is **not** equivariant. It picks "the first index whose type equals `target`"
— a choice that depends on the *labeling*, not on the abstract graph. If we permute the
input graph by σ, the first-occurring vertex in the tied class changes, and the promoted
vertex is no longer σ-related to the one promoted in the unpermuted run. So the clean
σ-commutes-with-everything argument doesn't survive.

The fix is to weaken equivariance to equivariance **up to the remaining symmetry group**,
and use an inductive argument on orbit sizes. The rest of this file lays that out.

--------------------------------------------------------------------------------
## 3. Conceptual apparatus required

These are definitions/results that do not yet exist in the file and must be built.
They are independent of the canonizer itself — they are general facts about graph
automorphisms — so they can be developed in isolation.

### 3.1  The automorphism group Aut(G)

  `Aut (G : AdjMatrix n) : Subgroup (Equiv.Perm (Fin n))`
    := { σ | ∀ i j, G.adj (σ i) (σ j) = G.adj i j }

Equivalently: σ ∈ Aut G iff relabeling G by σ gives G back. This is the group of
"hidden symmetries" that convergence can never distinguish, because any graph-local
invariant (path counts, degree, …) is by definition Aut-invariant.

### 3.2  Orbits of Aut(G) on vertices

  `orbit (G : AdjMatrix n) (v : Fin n) : Set (Fin n) := { σ v | σ ∈ Aut G }`

Two vertices are in the same orbit iff an automorphism maps one to the other.

### 3.3  Isomorphism ≃ as permutation existence (bridge lemma)

The inductive `Isomorphic` predicate (generated by refl/swap/trans) needs to be
shown equivalent to:

  `G ≃ H ↔ ∃ σ : Equiv.Perm (Fin n), ∀ i j, H.adj i j = G.adj (σ i) (σ j)`

One direction is by induction on Isomorphic (swap gives a transposition, and products
of transpositions are all of Sym(n)). The other direction writes σ as a product of
transpositions and applies `Isomorphic.swap` + `.trans`.

This bridge is the critical tool: it converts the syntactic inductive relation into
an extensional statement we can reason about with group theory.

--------------------------------------------------------------------------------
## 4. Proof outline of (→) for the full pipeline

Let σ ∈ Sym(n) be an automorphism of G (i.e. σ·G = G); write T₀ for the all-zeros
input. We prove, by induction on the number of tiebreaks performed so far, that at
every step of `orderVertices` the state is equivariant **under Aut(G)** (not all of
Sym(n) — only the remaining symmetries).

### 4.1  Stage A — convergence respects Aut(G)

**Claim.** If T is Aut(G)-invariant (i.e. T[σi] = T[i] for all σ ∈ Aut G), then
`convergeLoop` applied to (G,T) produces a T' that is also Aut(G)-invariant.

**Why.** `convergeOnce` reads `rankState.getFrom (n-1) i` and writes it into slot i.
The rank-from value at vertex i is a function of paths-from-i, which depends only on
the labeled-graph structure reachable from i. Any automorphism σ ∈ Aut G bijects
paths-from-i with paths-from-(σi) preserving edge labels and endpoint types (since T
is already Aut-invariant by hypothesis), so the multiset fed into `comparePathsFrom`
is identical for i and σi, hence they land in the same equivalence class, hence the
same rank.

This is the **Aut-equivariant analogue** of stage B in the old proof. The mechanics
(induction on depth, path-bijection) are the same; only the group being quantified
over shrinks from Sym(n) to Aut(G).

**Corollary.** After initial convergence, vertices in the same Aut(G)-orbit have
the same type.

### 4.2  Stage B — tiebreak refines the automorphism group

Let T be the converged types. Let t₀ be the smallest value that appears at least twice
in T (if none, we are done — all types are distinct, skip to stage D). Let V_{t₀} be
the set of indices with that type. By 4.1, V_{t₀} is a union of Aut(G)-orbits.

`breakTie T t₀` picks the **least-index element** v* of V_{t₀} and bumps everyone else
in V_{t₀} up by one. This produces T' with T'[v*] = t₀ and T'[w] = t₀+1 for every
other w in V_{t₀}.

**Claim.** Let G' := G with vertex types T'. Then

    Aut(G, T')  =  Stab_{Aut(G,T)}(v*)

i.e. the automorphisms of G that additionally preserve T' are precisely those that
fix v*. (Here Aut(G,T) means automorphisms of G that preserve the vertex typing T.)

**Why.** An automorphism σ preserves T' iff it sends v* to another type-t₀ vertex, and
there is exactly one: v* itself. So σ v* = v*. Conversely any σ ∈ Aut(G,T) fixing v*
sends V_{t₀}\{v*} to itself and so preserves T'.

**Orbit-size decrease.** This is a strictly smaller group unless V_{t₀} was already a
singleton (ruled out by choice). So each tiebreak strictly shrinks the typed-automorphism
group. After at most n tiebreaks it is trivial — all types distinct.

### 4.3  Stage C — choice of v* does not affect the canonical form

This is the crux of the whole argument, and the thing the old proof never had to
establish. `breakTie` picks v* by lexicographic index. A different graph labeling would
make a *different* vertex the "first occurrence." We must show this doesn't matter.

**Claim.** Suppose v*₁ and v*₂ are both in V_{t₀} (and hence in the same Aut(G,T)-orbit
by 4.1). Let T'₁ and T'₂ be the results of promoting v*₁ vs v*₂. Then the final output
of the full algorithm, starting from T'₁ vs T'₂, is **the same adjacency matrix** once
relabeling is applied.

**Why.** Let τ ∈ Aut(G,T) with τ v*₁ = v*₂ (exists because they are in the same orbit).
Then T'₂ = τ · T'₁ (the promoted-type array, permuted by τ, matches the other choice),
and G = τ · G (τ is an automorphism). So the pair (G, T'₂) equals τ·(G, T'₁). By
Aut(G)-equivariance of the *remaining* pipeline (stages A, further tiebreaks, labeling
— each proved by induction), the final canonized matrix is identical. The intuition:
you can "pre-apply τ" to the labeling, but the canonization step at the very end sorts
all of that away.

This step is what replaces the clean full-Sym(n) equivariance of the old proof. The
induction hypothesis is: for any Aut(G,T)-related pair of inputs, the remaining pipeline
produces the same canonical output. The base case is Aut(G,T) = {id}, where the claim
is trivial.

### 4.4  Stage D — final relabeling is well-defined and canonical

Once all types are distinct, `computeDenseRanks` gives a total order on vertices, and
`labelEdgesAccordingToRankings` produces a unique matrix: position (p,q) carries the
edge G.adj(w_p)(w_q) where w_p is the unique vertex of dense-rank p. Since the vertex
types were produced by an Aut(G)-invariant process, any two isomorphic graphs end with
type arrays that are related by the isomorphism — and relabeling by sorted type erases
the isomorphism entirely, giving equal outputs.

Combining: for G ≃ H via σ (i.e. σ·G = H, σ a permutation not necessarily in Aut G),
    run 0 H = run 0 (σ·G)
           = (canonize stages are equivariant under σ, modulo tiebreak choice)
           = run 0 G                                                            ∎

--------------------------------------------------------------------------------
## 5. Assumptions and caveats

**A1. Convergence is strong enough.** The algorithm's correctness does **not** require
that `convergeLoop` detect every Aut(G)-symmetry — only that the types it outputs are
Aut(G)-invariant (stage 4.1). Weaker refinements mean more tiebreaks are needed, but the
final result is unchanged. So "the Weisfeiler-Leman-level completeness" question is
orthogonal to canonicity: even 1-WL convergence would suffice, given tiebreak+refinement.

**A2. Tiebreak targets a stable feature.** `breakTie` is called with `target = targetPosition`,
i.e. with the loop counter, not with the smallest tied type. For this to do the right
thing we need: after `targetPosition` iterations, the type value at the "next slot to
resolve" is exactly `targetPosition`. This is **an invariant of the algorithm**, not
obviously true from the definitions, and would need its own lemma (something like
"converged types are always a prefix of ℕ"). If this invariant is ever broken — e.g. by
a non-dense rank assignment — the tiebreak either fires on nothing or promotes the wrong
class, and the whole argument has to re-examine `assignRanks` / `computeDenseRanks`
monotonicity.

**A3. Integer overflow / Fin bounds.** The `set!` / `getD` usage never fails at
proof-time because the indices used are always `< n`, but each `set!` call carries a
proof obligation that the underlying proof would need to discharge (usually via a
`by decide` or a bound-tracking invariant).

**A4. Termination of `convergeLoop`.** Given `state.vertexCount` as the fuel parameter,
this loop may terminate early or may exhaust fuel. Correctness doesn't need actual
convergence — just that each iteration is monotone refinement. But if we want to claim
the ranks at fuel-exhaustion are Aut(G)-invariant, we need a lemma that says any fixed
point of `convergeOnce`, reachable or not, is Aut-invariant. (It is.)

**A5. The equivalence Isomorphic ↔ ∃σ.** §3.3 is assumed throughout. Its proof is
standard but nontrivial: Sym(n) is generated by transpositions.

--------------------------------------------------------------------------------
## 6. What to salvage from the old proof file

Sections §1–§4 of `LeanGraphCanonizerV4Correctness.lean` survive verbatim:
AdjMatrix extensionality, swap involution, Isomorphic being an equivalence relation,
and `run_isomorphic_to_input`. The (←) direction of the main theorem still works.

Section §5 (pipeline equivariance under full Sym(n)) must be **weakened** to
equivariance under Aut(G), as described in 4.1. Everything mentioning σ : Equiv.Perm
needs a side-hypothesis `σ ∈ Aut G`.

Section §6 (`run_swap_invariant`) is false as stated — swapping labels generally
changes `breakTie`'s chosen representative. The correct replacement is §4.3 above:
"the final canonized matrix is invariant under swaps that are automorphisms of G."
For swaps that are not automorphisms, equality only holds *after* canonization, which
is exactly the statement we are trying to prove.

Section §7 (main theorems) stays structurally the same but calls into the new lemmas.

--------------------------------------------------------------------------------
## 7. Suggested proof-development order

1. Define `Aut` and `orbit`; prove Aut is a subgroup; prove orbits partition Fin n.
2. Prove §3.3 bridge lemma (Isomorphic ↔ ∃σ). All downstream reasoning uses σ.
3. Redo stages A/B of the old proof under the Aut(G) restriction.
4. State and prove stage 4.1 (convergence respects Aut(G)).
5. State and prove stage 4.2 (tiebreak shrinks the typed-automorphism group).
6. State and prove stage 4.3 (the hard one: choice-independence via orbit transitivity).
7. Discharge assumption A2 (converged types form a prefix of ℕ) as a separate lemma.
8. Assemble into the final `run_canonical` theorem.

Steps 1–2 and 7 can proceed in parallel with the main argument. Step 6 is the
conceptual bottleneck and should be the focus of effort.
-/

namespace Graph

/- Intentionally empty: this file is a design document. Once the plan above is
   carried out, real definitions and theorems would replace this placeholder. -/

end Graph
