#!/usr/bin/env python3
"""
ROUTE C — F1: recover the additive/affine (𝔽_p^d) structure from the ABSTRACT graph.

Route C needs the vertex set as a vector space so that `z - t` (and later Q(z-t)) is defined.
The family-AGNOSTIC recovery (keeps the "1 engine" merge): the translation group is the SOCLE
of Aut.  These graphs are affine-primitive, so

    soc(Aut) = O_p(Aut) = the regular elementary-abelian translation group  T ≅ (𝔽_p)^d,

and a basis of T gives coordinates, any vertex as origin gives the affine structure.  O_p from
generators is standard poly group theory (normal closures), hostable on the existing
`PermutationGroup.cs` Schreier–Sims substrate.

THIS PROBE validates the ALGORITHM on the real graphs, from GENERATORS only (the harness's job
is to harvest Aut; here we hand F1 a generating set = translations + isometries, then SCRAMBLE):
  (1) recovered O_p (via normal closures) == the true translation group T  (method-correct);
  (2) scramble-invariant (recovery commutes with relabelling);
  (3) T is regular + elementary-abelian of order q^d;
  (4) the recovered coordinates make the connection set (neighbours of any origin) a QUADRIC
      CONE  -- degree-2 vanishing dim = 1 -- i.e. F1 hands A1 a valid coordinatization.

Scope: odd q (Route C's target; -1 is a p'-element so G₀ is a p'-group ⟹ O_p(G)=T cleanly).
char 2 recovers T the same way but needs Aut's p'-part (e.g. S_5 for Clebsch) -- the char-2 track.
The fact "soc = O_p = T" is the affine-primitive socle theorem (cited), not something the probe
discovers; the probe validates the constructive recovery + coordinatization on real graphs.
"""
import itertools, random
from model_gap import make_Q, add, sub, isoclass

# ---- permutation ops (perms are tuples; p[i] = image of i) ----
def comp(a, b):                     # apply b then a
    return tuple(a[b[i]] for i in range(len(a)))
def inv(p):
    r = [0]*len(p)
    for i, x in enumerate(p): r[x] = i
    return tuple(r)
def ident(n): return tuple(range(n))
def order(p):
    n = len(p); seen = [False]*n; o = 1
    for i in range(n):
        if not seen[i]:
            c = 0; j = i
            while not seen[j]: seen[j] = True; j = p[j]; c += 1
            # lcm
            a, b = o, c
            while b: a, b = b, a % b
            o = o*c//a
    return o
def is_pgroup(K, p):
    for g in K:
        o = order(g)
        while o % p == 0: o //= p
        if o != 1: return False
    return True
def conj(x, s): return comp(comp(s, x), inv(s))

def normal_closure(g, gens, cap):
    """<g^G> as a subgroup, or None if it exceeds cap (=> not a small p-group)."""
    cl = {g}; fr = [g]
    while fr:
        x = fr.pop()
        for s in gens:
            for y in (conj(x, s), conj(x, inv(s))):
                if y not in cl:
                    cl.add(y); fr.append(y)
                    if len(cl) > cap: return None
    # subgroup generated by the conjugacy-class closure
    base = list(cl); K = set(cl); K.add(ident(len(g))); fr = list(K)
    while fr:
        x = fr.pop()
        for h in base:
            y = comp(x, h)
            if y not in K:
                K.add(y); fr.append(y)
                if len(K) > cap: return None
    return K

def recover_Op(gens, p, cap):
    """O_p(G) = join of the normal closures <g^G> that are p-groups (each ⊆ O_p; join = O_p)."""
    n = len(gens[0]); collected = []
    for g in gens:
        o = order(g); oo = o
        while oo % p == 0: oo //= p
        if oo != 1: continue                     # g not a p-element
        K = normal_closure(g, gens, cap)
        if K is not None and is_pgroup(K, p): collected.append(K)
    # join
    J = {ident(n)}; base = [x for K in collected for x in K]; fr = list(base)
    J.update(base)
    while fr:
        x = fr.pop()
        for h in base:
            y = comp(x, h)
            if y not in J:
                J.add(y); fr.append(y)
                if len(J) > cap: return None
    return J

# ---- signed coordinate permutations preserving Q, of order coprime to p ----
def monomial_isometries(V, Q, q, d, p):
    idx = {v: i for i, v in enumerate(V)}; out = []
    for sigma in itertools.permutations(range(d)):
        for signs in itertools.product((1, q-1), repeat=d):
            def gv(x, sigma=sigma, signs=signs):
                y = [0]*d
                for i in range(d): y[sigma[i]] = (signs[i]*x[i]) % q
                return tuple(y)
            if all(Q(gv(x)) == Q(x) for x in V):
                perm = tuple(idx[gv(V[i])] for i in range(len(V)))
                o = order(perm); oo = o
                while oo % p == 0: oo //= p
                if oo == o and perm != ident(len(V)):   # order coprime to p, nontrivial
                    out.append(perm)
    # dedup
    seen = set(); uniq = []
    for perm in out:
        if perm not in seen: seen.add(perm); uniq.append(perm)
    return uniq

def rref_rank(rows, q):
    rows = [r[:] for r in rows]
    if not rows: return 0
    ncols = len(rows[0]); r = 0
    for c in range(ncols):
        piv = next((i for i in range(r, len(rows)) if rows[i][c] % q), None)
        if piv is None: continue
        rows[r], rows[piv] = rows[piv], rows[r]
        invp = pow(rows[r][c] % q, q-2, q)
        rows[r] = [(x*invp) % q for x in rows[r]]
        for i in range(len(rows)):
            if i != r and rows[i][c] % q:
                f = rows[i][c]; rows[i] = [(a-f*b) % q for a, b in zip(rows[i], rows[r])]
        r += 1
        if r == len(rows): break
    return r

def run(d, q, eps, rng):
    p = q                                     # q prime in this probe
    V = list(itertools.product(range(q), repeat=d)); n = len(V)
    idx = {v: i for i, v in enumerate(V)}; Q = make_Q(d, q, eps)
    nm = f"VO^{'+' if eps > 0 else '-'}_{d}({q})"

    # labelled adjacency (edge = nonzero isotropic difference) + true translations
    edges = {(i, j) for i in range(n) for j in range(n)
             if i != j and isoclass(Q, q, d, sub(V[i], V[j], q, d)) == 1}
    def transl(w): return tuple(idx[add(V[i], w, q, d)] for i in range(n))
    T_true = {transl(w) for w in V}
    basis_trans = [transl(tuple(1 if k == i else 0 for k in range(d))) for i in range(d)]
    isoms = monomial_isometries(V, Q, q, d, p)

    # SCRAMBLE by a random relabelling pi (conjugate everything; recovery sees only scrambled data)
    pi = list(range(n)); rng.shuffle(pi); pi = tuple(pi); pii = inv(pi)
    scr = lambda perm: comp(comp(pi, perm), pii)
    gens = [scr(g) for g in (basis_trans + isoms)]
    T_true_s = {scr(g) for g in T_true}
    edges_s = {(pi[i], pi[j]) for (i, j) in edges}

    # (1)-(3) recover O_p and validate
    Op = recover_Op(gens, p, cap=n*q*q)
    ok_eq = (Op == T_true_s)
    regular = all(all(g[i] != i for i in range(n)) for g in Op if g != ident(n)) and len(Op) == n
    elem_ab = is_pgroup(Op, p) and all(order(g) in (1, p) for g in Op)

    # (4) coordinatize via a basis of the recovered T, check the cone
    o0 = 0
    Tlist = [g for g in Op]
    # greedy F_p-basis of T (subgroup grows by factor p each add)
    def gen_sub(gs):
        S = {ident(n)}; fr = [ident(n)]
        while fr:
            x = fr.pop()
            for h in gs:
                y = comp(x, h)
                if y not in S: S.add(y); fr.append(y)
        return S
    basis = []; cur = {ident(n)}
    for g in Tlist:
        if g == ident(n): continue
        S = gen_sub(basis + [g])
        if len(S) > len(cur): basis.append(g); cur = S
        if len(cur) == n: break
    # coordinate of each group element by brute over (Z_p)^d (p^d combos)
    powers = [[ident(n)] for _ in basis]
    for k, b in enumerate(basis):
        for _ in range(p-1): powers[k].append(comp(powers[k][-1], b))
    elt2coord = {}
    for c in itertools.product(range(p), repeat=len(basis)):
        e = ident(n)
        for k, ck in enumerate(c): e = comp(e, powers[k][ck])
        elt2coord[e] = c
    vcoord = {}
    for e, c in elt2coord.items(): vcoord[e[o0]] = c        # vertex e(o0) has coord c
    neigh = [x for x in range(n) if (o0, x) in edges_s]
    monos = [(i, j) for i in range(d) for j in range(i, d)]
    rows = [[(vcoord[x][i]*vcoord[x][j]) % q for (i, j) in monos] for x in neigh]
    vanish = len(monos) - rref_rank(rows, q)

    print(f"{nm:12s} n={n:4d} |isoGens|={len(isoms):3d} |Op|={len(Op) if Op else '--':>4} "
          f"| Op==T:{str(ok_eq):5s} regular:{str(regular):5s} elemAb:{str(elem_ab):5s} "
          f"| coords: |neigh|={len(neigh):4d} coneVanishDim={vanish} "
          f"{'OK' if (ok_eq and regular and elem_ab and vanish == 1) else '*** CHECK ***'}")

if __name__ == "__main__":
    print("=== Route C F1: recover the (𝔽_p)^d translation group T = O_p(Aut) from scrambled generators ===")
    print("    validate: Op==T, regular, elementary-abelian, and coordinates make the cone a quadric (vanishDim=1)\n")
    rng = random.Random(12345)
    for q in (3, 5):
        for eps in (-1, 1):
            run(4, q, eps, rng)
