#!/usr/bin/env python3
"""Maintenance tool for the GraphCanonizationProofs theorem index.

Subcommands:
  check                Sanity-check the 'Used By' column against the source.
  rewrite              Regenerate the index file(s), preserving description /
                       notes and emitting a chosen set of optional columns.
  split                One-shot: split TheoremIndex.md into the four-file
                       layout (active vs. archived × public vs. private),
                       grouped by source file path.

Optional columns (flags on `rewrite` / `split`):
  --with-used-by       Recompute and include the 'Used By' column. For
                       `@[simp]` theorems this column is left empty since they
                       are usually applied implicitly via the `simp` tactic.
  --with-line-numbers  Include a 'Line' column with a source-line *range*
                       covering the declaration's header (attached doc
                       comment / attributes) plus its body.

Discovery (flag on `rewrite`):
  --include-new        Append placeholder entries for source declarations not
                       yet in the index. Use after adding new lemmas / new
                       files (e.g. ChainDescent.lean) so they appear in the
                       regenerated index for description-filling.

Index layout (always emitted as four files post-rewrite):
  GraphCanonizationProofs/PublicTheoremIndex.md         — active, public
  GraphCanonizationProofs/PrivateTheoremIndex.md        — active, private
  GraphCanonizationProofs/Archive/PublicTheoremIndex.md  — archived, public
  GraphCanonizationProofs/Archive/PrivateTheoremIndex.md — archived, private

The rewrite command reads from whichever of these (or the legacy single /
two-file layouts) currently exist on disk and re-emits the four-file
layout, automatically moving an entry between the active and archived
indices when its source file moves into or out of `Archive/`. Hand-written
description / notes columns are preserved across moves.

Source-scan scope: all `.lean` files under `GraphCanonizationProofs/`,
excluding the `.lake/` build / package cache. Files under `Archive/...`
are classified as *archived*; everything else as *active*. Section
headers use the full path relative to `GraphCanonizationProofs/`
(e.g. `## Archive/V4/FullCorrectness/Basic.lean`).
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

# ---------------------------------------------------------------------------
# Repo / file layout
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent
ROOT = REPO_ROOT / "GraphCanonizationProofs"

SINGLE_INDEX = ROOT / "TheoremIndex.md"

# Active (non-archived) indices.
ACTIVE_PUBLIC_INDEX = ROOT / "PublicTheoremIndex.md"
ACTIVE_PRIVATE_INDEX = ROOT / "PrivateTheoremIndex.md"

# Archived indices: live next to the archived Lean source under `Archive/`.
ARCHIVE_PUBLIC_INDEX = ROOT / "Archive" / "PublicTheoremIndex.md"
ARCHIVE_PRIVATE_INDEX = ROOT / "Archive" / "PrivateTheoremIndex.md"

# Legacy aliases kept for migration. The two-file split layout pre-dating
# the active/archived split lived at PUBLIC_INDEX / PRIVATE_INDEX (i.e. the
# same paths we now use for ACTIVE_PUBLIC_INDEX / ACTIVE_PRIVATE_INDEX).
PUBLIC_INDEX = ACTIVE_PUBLIC_INDEX
PRIVATE_INDEX = ACTIVE_PRIVATE_INDEX

ALL_INDEX_FILES = (
    ACTIVE_PUBLIC_INDEX,
    ACTIVE_PRIVATE_INDEX,
    ARCHIVE_PUBLIC_INDEX,
    ARCHIVE_PRIVATE_INDEX,
)

# A source path is considered archived iff it sits anywhere under `Archive/`
# (relative to ROOT). The four-file layout pivots on this.
ARCHIVE_PREFIX = "Archive/"


def is_archived_path(path_str: str) -> bool:
    """True if the given source-relative path lives under `Archive/`."""
    if not path_str:
        return False
    return path_str.replace("\\", "/").startswith(ARCHIVE_PREFIX)

# Names auto-generated by attributes/structures rather than written as
# explicit declarations (e.g. `@[ext]` on a structure synthesises `<S>.ext`).
# Maps the auto-generated name to the source file where its origin sits
# (relative to ROOT).
AUTOGENERATED: dict[str, str] = {
    "AdjMatrix.ext": "Archive/V4/FullCorrectness/Basic.lean",
}

# Directory components excluded from the source scan — build artefacts and
# package caches we don't want to walk.
EXCLUDED_DIRS = {".lake"}


# ---------------------------------------------------------------------------
# Lean source parser
# ---------------------------------------------------------------------------
DECL_RE = re.compile(
    r"^\s*"
    r"(?:@\[[^\]]*\]\s*)*"
    r"(?:private\s+|protected\s+|noncomputable\s+|partial\s+|unsafe\s+)*"
    r"(theorem|lemma|def|instance|abbrev|structure|class|inductive)"
    r"\s+([^\s:({\[]+)",
    re.UNICODE,
)
DECL_LINE_RE = re.compile(
    r"^\s*"
    r"((?:@\[[^\]]*\]\s*)*)"
    r"((?:private\s+|protected\s+|noncomputable\s+|partial\s+|unsafe\s+)*)"
    r"(theorem|lemma|def|instance|abbrev|structure|class|inductive)"
    r"\s+([^\s:({\[]+)",
    re.UNICODE,
)


def strip_comments(body: str) -> str:
    """Strip Lean block (nesting-aware) and line comments."""
    out: list[str] = []
    i, n, depth = 0, len(body), 0
    while i < n:
        two = body[i:i + 2]
        if two == "/-":
            depth += 1
            i += 2
        elif two == "-/" and depth > 0:
            depth -= 1
            i += 2
        elif depth > 0:
            i += 1
        elif two == "--":
            while i < n and body[i] != "\n":
                i += 1
        else:
            out.append(body[i])
            i += 1
    return "".join(out)


def _classify_lines(text: str) -> list[str]:
    """Per-line classification used by header-range detection.

    Returns a list of tags, one per line (split on '\\n'). Tags:
      - 'blank' : empty / whitespace-only line.
      - 'attr'  : top-level attribute line (`@[simp]`, `@[ext]`, ...).
      - 'doc'   : a line inside or making up a `/-- ... -/` doc comment.
      - 'sect'  : a line inside or making up a `/-! ... -/` section comment.
      - 'cmt'   : a line inside any other `/- ... -/` block comment.
      - 'code'  : anything else (regular Lean source).

    Doc-comment classification powers header-range expansion: when walking
    back from a declaration line to find the start of its header, we
    include contiguous `attr` and `doc` lines and stop at the first
    blank / sect / cmt / code line.
    """
    lines = text.split("\n")
    kinds: list[str] = []
    block_depth = 0
    block_kind: str | None = None  # 'doc' | 'sect' | 'cmt'
    for line in lines:
        stripped = line.strip()
        if block_depth > 0:
            kind = block_kind or "cmt"
        elif not stripped:
            kind = "blank"
        elif stripped.startswith("@["):
            # `@[simp] theorem foo := ...` is a declaration line (the
            # attribute lives on the keyword's own line). Only treat the
            # line as a pure attribute when no decl keyword follows on
            # the same line — otherwise the next decl's header walkback
            # would incorrectly absorb this declaration's header.
            kind = "code" if DECL_LINE_RE.match(line) else "attr"
        elif stripped.startswith("/--"):
            kind = "doc"
        elif stripped.startswith("/-!"):
            kind = "sect"
        elif stripped.startswith("/-"):
            kind = "cmt"
        else:
            kind = "code"

        # Advance block_depth / block_kind across this line's open/close
        # markers so the *next* line's classification is correct.
        i = 0
        while i < len(line):
            two = line[i:i + 2]
            three = line[i:i + 3]
            if two == "/-":
                if block_depth == 0:
                    if three == "/--":
                        block_kind = "doc"
                    elif three == "/-!":
                        block_kind = "sect"
                    else:
                        block_kind = "cmt"
                block_depth += 1
                i += 2
            elif two == "-/" and block_depth > 0:
                block_depth -= 1
                if block_depth == 0:
                    block_kind = None
                i += 2
            elif two == "--" and block_depth == 0:
                break  # rest of line is a Lean line comment
            else:
                i += 1
        kinds.append(kind)
    return kinds


_TERMINATOR_RE = re.compile(r"^\s*(namespace|end|section)\b")
_ANON_INSTANCE_RE = re.compile(r"^\s*(?:@\[[^\]]*\]\s*)*instance\s*[:({\[]")


def _is_decl_terminator(line: str) -> bool:
    """A line that should not be folded into the *preceding* declaration's
    end_line. Used by the walk-forward end-finder so that an inductive's
    range stops at the next `namespace`/`end`/`section`/anonymous-instance
    line rather than absorbing sibling code into the range."""
    if _TERMINATOR_RE.match(line):
        return True
    # Anonymous `instance : Foo := ...` lines: the explicit-declaration
    # parser skips these (no identifier follows the keyword), so they
    # would otherwise be silently attributed to the previous decl.
    if _ANON_INSTANCE_RE.match(line):
        return True
    return False


def parse_lean_file(path: Path) -> list[dict]:
    """Return list of declarations.

    Each entry has keys:
      - name        : declaration identifier.
      - line        : 1-indexed line of the declaration keyword
                      (theorem/def/lemma/...). Same as the historical
                      `line` field.
      - header_start: 1-indexed line where the declaration's *header*
                      starts — the first contiguous attached attribute or
                      doc-comment line above `line`, falling back to
                      `line` itself when there are none.
      - end_line    : 1-indexed last line of the declaration's body
                      (excluding trailing blank lines and the next
                      declaration's header).
      - is_private  : has the `private` modifier on the keyword line.
      - is_simp     : has the `@[simp]` attribute on the keyword line.
      - body        : full text from the declaration keyword to the next
                      declaration's header_start (unchanged semantics).
    """
    text = path.read_text()
    lines = text.split("\n")
    line_kinds = _classify_lines(text)

    decls: list[dict] = []
    for i, line in enumerate(lines):
        # Don't treat declarations inside any kind of block comment as real.
        if line_kinds[i] in ("doc", "sect", "cmt"):
            continue
        m = DECL_LINE_RE.match(line)
        if not m:
            continue
        attrs, modifiers, _kind, name = m.groups()
        if not (name[0].isalpha() or name[0] == "_"):
            continue
        decls.append({
            "name": name,
            "line": i + 1,           # 1-indexed
            "_line_idx": i,
            "is_private": bool(re.search(r"\bprivate\b", modifiers)),
            "is_simp": "@[simp" in (attrs or ""),
        })

    # Pass 1: header_start (depends only on the lines above each decl).
    header_starts: list[int] = []  # 0-indexed
    for d in decls:
        h = d["_line_idx"] - 1
        while h >= 0 and line_kinds[h] in ("attr", "doc"):
            h -= 1
        header_starts.append(h + 1)

    # Pass 2: end_line + body. Each decl owns the lines from its
    # `_line_idx` up to the *next* decl's header_start, exclusive. The
    # end_line is the last source line that actually belongs to the
    # declaration — we walk forward and stop at the first structural
    # marker (namespace/end/section/section comment/anonymous instance),
    # so a declaration's range is not padded with sibling namespace
    # housekeeping or skipped anonymous instances.
    for j, d in enumerate(decls):
        next_hs = header_starts[j + 1] if j + 1 < len(decls) else len(lines)
        e = d["_line_idx"]
        for k in range(d["_line_idx"] + 1, next_hs):
            if line_kinds[k] == "sect":
                break
            stripped_k = lines[k].strip()
            if not stripped_k:
                continue
            if _is_decl_terminator(lines[k]):
                break
            e = k
        d["header_start"] = header_starts[j] + 1  # 1-indexed
        d["end_line"] = e + 1                     # 1-indexed
        d["body"] = "\n".join(lines[d["_line_idx"]:next_hs])
        del d["_line_idx"]
    return decls


def _iter_lean_files() -> list[Path]:
    """All .lean files under ROOT, skipping `.lake/` build/package trees.

    Era-agnostic: scans both active locations (e.g. `ChainDescent.lean`) and
    archived ones (e.g. `Archive/V4/FullCorrectness/...`).
    """
    out: list[Path] = []
    for path in ROOT.rglob("*.lean"):
        rel = path.relative_to(ROOT)
        if any(part in EXCLUDED_DIRS for part in rel.parts):
            continue
        out.append(path)
    return sorted(out)


def parse_all_lean() -> dict[str, dict]:
    """name -> {path, line, is_private, is_simp, body, stripped_body}."""
    out: dict[str, dict] = {}
    for path in _iter_lean_files():
        for d in parse_lean_file(path):
            d["path"] = path.relative_to(ROOT)
            d["stripped_body"] = strip_comments(d["body"])
            out[d["name"]] = d
    return out


# ---------------------------------------------------------------------------
# Markdown index parser
# ---------------------------------------------------------------------------
ROW_RE = re.compile(r"^\|\s*(.*?)\s*\|\s*$")
SECTION_RE = re.compile(r"^##\s+(.+?)\s*$")


def split_row(line: str) -> list[str] | None:
    if not line.startswith("|") or not line.rstrip().endswith("|"):
        return None
    inner = line.rstrip()[1:-1]
    return [c.strip() for c in inner.split("|")]


def parse_index_file(path: Path) -> tuple[list[dict], dict[str, str]]:
    """Returns (entries, section_to_path_hint).

    Each entry is a dict {name, used_by[list], description, notes, section}.
    `section_to_path_hint` is best-effort: if a section header looks like
    `path/to/file.lean`, it maps the section name to that path string.
    """
    entries: list[dict] = []
    section: str | None = None
    section_path_hint: dict[str, str] = {}
    if not path.exists():
        return [], {}
    for line in path.read_text().splitlines():
        m_sec = SECTION_RE.match(line)
        if m_sec:
            section = m_sec.group(1).strip()
            if section.endswith(".lean"):
                section_path_hint[section] = section
            continue
        cells = split_row(line)
        if cells is None:
            continue
        # Header / separator rows: skip them.
        if not cells or cells[0].strip("`") in ("Name", "") or set("".join(cells).replace(" ", "")) <= set("-"):
            continue
        if not cells[0].startswith("`"):
            continue
        name = cells[0].strip().strip("`").strip()
        # Locate description / notes / used_by columns by header heuristic:
        # rows have variable column counts depending on file flavour. We
        # always take the LAST two cells as (description, notes).
        if len(cells) < 3:
            continue
        notes = cells[-1]
        description = cells[-2]
        # Any in-between cells are optional columns (Used By, Line).
        # We only care about Used By here; skip Line if present. The Line
        # column is either a bare integer (legacy) or a `start-end` range
        # (post header-range update).
        middle = cells[1:-2]
        used_by_raw = ""
        for c in middle:
            cs = c.strip()
            if cs.isdigit():
                continue
            if re.match(r"^\d+\s*[-–]\s*\d+$", cs):
                continue
            used_by_raw = c
            break
        used_by = parse_used_by_cell(used_by_raw)
        entries.append({
            "name": name,
            "used_by": used_by,
            "description": description,
            "notes": notes,
            "section": section,
        })
    return entries, section_path_hint


def parse_used_by_cell(cell: str) -> list[str]:
    cell = cell.strip()
    if cell in ("—", "-", ""):
        return []
    return [
        x.strip().strip("`")
        for x in cell.split(",")
        if x.strip().strip("`")
    ]


def detect_layout() -> str:
    """Identify the index layout present on disk.

    Returns one of:
      - 'four'   : the four-file active/archive × public/private layout.
      - 'split'  : the legacy two-file public/private layout (active-only).
      - 'single' : the original single-file `TheoremIndex.md` layout.

    Detection prefers the most-evolved layout that has any file present:
    if any of the archive indices exist, we're in 'four'; otherwise if
    either active index exists, 'split'; otherwise 'single'.
    """
    if ARCHIVE_PUBLIC_INDEX.exists() or ARCHIVE_PRIVATE_INDEX.exists():
        return "four"
    if ACTIVE_PUBLIC_INDEX.exists() or ACTIVE_PRIVATE_INDEX.exists():
        return "split"
    return "single"


def load_existing_index() -> tuple[list[dict], dict[str, str]]:
    """Read whichever index files exist and merge their entries.

    Reads every layout file that currently exists on disk (including the
    legacy single and two-file variants) and concatenates their entries.
    Hand-written description / notes columns are preserved across moves
    between active and archive indices — when a Lean file is moved into
    `Archive/`, the next rewrite migrates its entries without losing the
    notes column.

    Duplicate names (same declaration appearing in more than one source
    file — should not happen in practice but is defensive) keep only the
    first occurrence.
    """
    all_entries: list[dict] = []
    all_hints: dict[str, str] = {}
    seen: set[str] = set()
    for f in (*ALL_INDEX_FILES, SINGLE_INDEX):
        if not f.exists():
            continue
        entries, hints = parse_index_file(f)
        all_hints.update(hints)
        for e in entries:
            if e["name"] in seen:
                continue
            seen.add(e["name"])
            all_entries.append(e)
    return all_entries, all_hints


# ---------------------------------------------------------------------------
# Used-By computation
# ---------------------------------------------------------------------------
def compute_used_by_map(source: dict[str, dict]) -> dict[str, set[str]]:
    """For each declaration A in `source`, find all other declarations B whose
    body textually references A (last-segment-as-word matching, with fallback
    to qualified-name when the last segment is ambiguous)."""
    last_seg_count: dict[str, int] = defaultdict(int)
    for name in source:
        last_seg_count[name.split(".")[-1]] += 1

    actual: dict[str, set[str]] = defaultdict(set)
    possible: dict[str, set[str]] = defaultdict(set)

    decls = list(source.items())
    for A, A_info in decls:
        last_seg = A.split(".")[-1]
        is_ambig = last_seg_count[last_seg] > 1
        if is_ambig:
            definite_pat = re.compile(rf"(?<![\w.]){re.escape(A)}(?!\w)")
            possible_pat: re.Pattern | None = re.compile(
                rf"(?:(?<=[\w]))\.{re.escape(last_seg)}\b"
            )
        else:
            definite_pat = re.compile(rf"\b{re.escape(last_seg)}\b")
            possible_pat = None
        for B, B_info in decls:
            if B == A:
                continue
            body = B_info["stripped_body"]
            if definite_pat.search(body):
                actual[A].add(B)
            elif possible_pat is not None and possible_pat.search(body):
                possible[A].add(B)
    # Stitch: also include possible-only matches as actual users (we err on
    # the side of recording references; the check command flags ambiguity).
    for A, users in possible.items():
        actual[A] |= users
    return actual


# ---------------------------------------------------------------------------
# `check` subcommand  (the original behaviour)
# ---------------------------------------------------------------------------
def cmd_check(_args: argparse.Namespace) -> None:
    entries, _ = load_existing_index()
    declared_used_by = {e["name"]: set(e["used_by"]) for e in entries}
    index_names = {e["name"] for e in entries}
    source = parse_all_lean()

    print(f"Loaded {len(entries)} indexed entries from {detect_layout()} layout")
    print(f"Loaded {len(source)} declarations from Lean source files\n")

    last_seg_count: dict[str, int] = defaultdict(int)
    for name in source:
        last_seg_count[name.split(".")[-1]] += 1

    source_names = set(source) | set(AUTOGENERATED)
    not_found_in_source = sorted(
        a for a in index_names
        if a not in source_names and " " not in a and "(" not in a
    )

    skipped: list[str] = []
    ambiguous: list[str] = []
    actual: dict[str, set[str]] = defaultdict(set)
    possible: dict[str, set[str]] = defaultdict(set)

    for A in index_names:
        if " " in A or "(" in A:
            skipped.append(A)
            continue
        last_seg = A.split(".")[-1]
        is_ambig = last_seg_count[last_seg] > 1
        if is_ambig:
            ambiguous.append(A)
            definite_pat = re.compile(rf"(?<![\w.]){re.escape(A)}(?!\w)")
            possible_pat: re.Pattern | None = re.compile(
                rf"(?:(?<=[\w]))\.{re.escape(last_seg)}\b"
            )
        else:
            definite_pat = re.compile(rf"\b{re.escape(last_seg)}\b")
            possible_pat = None
        for B, info in source.items():
            if B == A:
                continue
            body = info["stripped_body"]
            if definite_pat.search(body):
                actual[A].add(B)
            elif possible_pat is not None and possible_pat.search(body):
                possible[A].add(B)

    real_disc: list[tuple[str, list[str], list[str]]] = []
    for A in sorted(index_names):
        if A in skipped:
            continue
        declared = declared_used_by[A]
        actual_in_idx = {n for n in actual[A] if n in index_names}
        all_in_idx = actual_in_idx | {n for n in possible[A] if n in index_names}
        false_pos = sorted(
            x for x in declared - all_in_idx
            if " " not in x and "(" not in x
        )
        missing = sorted(actual_in_idx - declared)
        if false_pos or missing:
            real_disc.append((A, false_pos, missing))

    if skipped:
        print(f"Skipped {len(skipped)} typeclass-instance descriptors\n")
    if not_found_in_source:
        print(f"Indexed names with no source declaration ({len(not_found_in_source)}):")
        for n in not_found_in_source:
            print(f"    {n}")
        print()
    if ambiguous:
        print(f"{len(ambiguous)} indexed names share their last segment "
              "(matched only by full qualified name):")
        for a in ambiguous:
            print(f"    {a}")
        print()

    fp_only = [d for d in real_disc if d[1] and not d[2]]
    miss_only = [d for d in real_disc if d[2] and not d[1]]
    both = [d for d in real_disc if d[1] and d[2]]

    print("=" * 64)
    print(f" REPORT 1: {len(fp_only) + len(both)} entries with FALSE POSITIVES")
    print(" (declared 'Used By' entries with no textual mention in source)")
    print("=" * 64 + "\n")
    for A, fps, _ in fp_only + both:
        print(f"--- {A} ---")
        for x in fps:
            print(f"      {x}")
        print()

    print("\n" + "=" * 64)
    print(f" REPORT 2: {len(miss_only) + len(both)} entries with MISSING REFERENCES")
    print(" (textual mentions in source absent from 'Used By')")
    print("=" * 64 + "\n")
    for A, _, missing in miss_only + both:
        print(f"--- {A} ---")
        for x in missing:
            print(f"      {x}")
        print()


# ---------------------------------------------------------------------------
# `rewrite` subcommand
# ---------------------------------------------------------------------------
def build_section_path_map(
    entries: list[dict],
    source: dict[str, dict],
    section_path_hints: dict[str, str],
) -> dict[str, str]:
    """Map an index section header to a source file path.

    Used to assign typeclass-instance entries (which have no Lean identifier)
    to the same file as the named theorems they sit alongside.

    Resolution order:
      1. Best-by-count from source-resolved entries in the section.
      2. The section-header hint (`## path/to/file.lean`) **only if** the
         hinted file still exists on disk. Stale hints from before an
         archival move are dropped — the inferred best path wins.
    """
    section_to_path: dict[str, str] = {}
    counts: dict[str, dict[str, int]] = defaultdict(lambda: defaultdict(int))
    for e in entries:
        sec = e["section"]
        if sec is None or e["name"] not in source:
            continue
        path_str = str(source[e["name"]]["path"])
        counts[sec][path_str] += 1
    for sec, dist in counts.items():
        # Pick the file path with the most entries in that section.
        best = max(dist.items(), key=lambda kv: kv[1])[0]
        section_to_path[sec] = best
    for sec, hint in section_path_hints.items():
        if (ROOT / hint).exists() and sec not in section_to_path:
            section_to_path[sec] = hint
    return section_to_path


def assemble_entries(
    existing: list[dict],
    source: dict[str, dict],
    section_to_path: dict[str, str],
) -> list[dict]:
    """Produce a list of fully-resolved entries.

    Each output entry carries:
      - name, used_by, description, notes : carried over from `existing`.
      - path                              : source file relative to ROOT.
      - line, header_start, end_line      : 1-indexed source positions
                                            (None if not resolvable from
                                            source, e.g. typeclass-instance
                                            descriptors).
      - is_private, is_simp               : visibility / attribute flags.
      - is_archived                       : True iff `path` lives under
                                            `Archive/`. The four-file
                                            renderer pivots on this.
    """
    out: list[dict] = []
    for e in existing:
        name = e["name"]
        if name in source:
            info = source[name]
            path_str = str(info["path"])
            line = info["line"]
            header_start = info["header_start"]
            end_line = info["end_line"]
            is_private = info["is_private"] or "private" in e["notes"].lower()
            is_simp = info["is_simp"] or "@[simp]" in e["notes"]
        else:
            path_str = (
                AUTOGENERATED.get(name)
                or section_to_path.get(e["section"], "")
            )
            line = None
            header_start = None
            end_line = None
            is_private = "private" in e["notes"].lower()
            is_simp = "@[simp]" in e["notes"]
        out.append({
            **e,
            "path": path_str,
            "line": line,
            "header_start": header_start,
            "end_line": end_line,
            "is_private": is_private,
            "is_simp": is_simp,
            "is_archived": is_archived_path(path_str),
        })
    return out


def render_used_by(items: list[str]) -> str:
    if not items:
        return "—"
    return ", ".join(f"`{x}`" for x in sorted(set(items), key=lambda s: s.lower()))


def render_line_range(r: dict) -> str:
    """Render the Line column as a `start-end` range.

    Uses header_start (the topmost attached attribute / doc-comment line
    above the declaration keyword) for the lower bound and end_line (last
    non-blank line before the next declaration's header) for the upper
    bound. Collapses to a single number when start == end, and falls back
    to '—' when neither bound is known (typeclass instances, autogenerated
    `.ext` lemmas, etc.).
    """
    start = r.get("header_start") or r.get("line")
    end = r.get("end_line") or r.get("line")
    if start is None and end is None:
        return "—"
    if start is None:
        start = end
    if end is None or end == start:
        return str(start)
    return f"{start}-{end}"


def render_table(
    rows: list[dict],
    *,
    with_used_by: bool,
    with_line_numbers: bool,
) -> list[str]:
    headers = ["Name"]
    if with_used_by:
        headers.append("Used By")
    if with_line_numbers:
        headers.append("Line")
    headers += ["Description", "Notes"]

    out: list[str] = []
    out.append("| " + " | ".join(headers) + " |")
    out.append("|" + "|".join("-" * (len(h) + 2) for h in headers) + "|")
    for r in rows:
        cells = [f"`{r['name']}`"]
        if with_used_by:
            cells.append(render_used_by(r["new_used_by"]))
        if with_line_numbers:
            cells.append(render_line_range(r))
        cells.append(r["description"] or "—")
        cells.append(r["notes"] or "—")
        out.append("| " + " | ".join(cells) + " |")
    return out


def render_index(
    entries: list[dict],
    *,
    title: str,
    description: str,
    with_used_by: bool,
    with_line_numbers: bool,
) -> str:
    # Group by path; preserve existing path order based on first appearance.
    path_order: list[str] = []
    by_path: dict[str, list[dict]] = defaultdict(list)
    for e in entries:
        if e["path"] not in by_path:
            path_order.append(e["path"])
        by_path[e["path"]].append(e)

    # Within a section, sort by header_start (falling back to line).
    # None bounds go last.
    def _sort_key(r: dict) -> tuple[int, int]:
        s = r.get("header_start") or r.get("line")
        return (1 if s is None else 0, s or 0)
    for p in by_path:
        by_path[p].sort(key=_sort_key)

    legend = ["## Legend", ""]
    if with_used_by:
        legend.append(
            "- **Used By**: Theorems/definitions that directly reference this one. "
            "Empty for `@[simp]` theorems (used implicitly via the `simp` tactic)."
        )
    if with_line_numbers:
        legend.append(
            "- **Line**: Source-line range `start-end` covering the declaration's "
            "header (attached doc comment / attributes) and its full body. "
            "Collapses to a single number when the declaration occupies one line."
        )
    legend.extend([
        "- **Description**: A short description of what the theorem proves.",
        "- **Notes**: `@[simp]` / `@[ext]` attributes, `private`, instances, "
        "or other special properties.",
        "",
    ])

    out: list[str] = [f"# {title}", "", description, ""]
    out.extend(legend)
    for p in path_order:
        if not p:
            continue
        out.append(f"## {p}")
        out.append("")
        out.extend(render_table(
            by_path[p],
            with_used_by=with_used_by,
            with_line_numbers=with_line_numbers,
        ))
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def discover_new_entries(
    existing: list[dict],
    source: dict[str, dict],
) -> list[dict]:
    """Source declarations not yet in the index, as fresh placeholder entries.

    Each new entry gets `description = "—"` and `notes = "—"` (per the index
    convention for empty cells). They show up in the regenerated index so a
    human can fill them in incrementally without losing newly-added lemmas.
    """
    already = {e["name"] for e in existing}
    new_entries: list[dict] = []
    for name, info in source.items():
        if name in already:
            continue
        new_entries.append({
            "name": name,
            "used_by": [],
            "description": "—",
            "notes": "—",
            "section": str(info["path"]),
        })
    return new_entries


_INDEX_TITLES = {
    ("active",  False): "Public Theorem Index — GraphCanonizationProofs",
    ("active",  True):  "Private Theorem Index — GraphCanonizationProofs",
    ("archive", False): "Archived Public Theorem Index — GraphCanonizationProofs",
    ("archive", True):  "Archived Private Theorem Index — GraphCanonizationProofs",
}

_INDEX_DESCRIPTIONS = {
    ("active", False): (
        "Index of public Lean theorems, lemmas, and definitions in the "
        "GraphCanonizationProofs project (active source), grouped by "
        "source file path. Archived counterparts live in "
        "`Archive/PublicTheoremIndex.md`."
    ),
    ("active", True): (
        "Index of private Lean theorems, lemmas, and definitions in the "
        "GraphCanonizationProofs project (active source), grouped by "
        "source file path. Archived counterparts live in "
        "`Archive/PrivateTheoremIndex.md`."
    ),
    ("archive", False): (
        "Index of public Lean theorems, lemmas, and definitions in the "
        "archived (`Archive/...`) portion of the GraphCanonizationProofs "
        "project, grouped by source file path. Active counterparts live "
        "in `../PublicTheoremIndex.md`."
    ),
    ("archive", True): (
        "Index of private Lean theorems, lemmas, and definitions in the "
        "archived (`Archive/...`) portion of the GraphCanonizationProofs "
        "project, grouped by source file path. Active counterparts live "
        "in `../PrivateTheoremIndex.md`."
    ),
}

_INDEX_PATHS = {
    ("active",  False): ACTIVE_PUBLIC_INDEX,
    ("active",  True):  ACTIVE_PRIVATE_INDEX,
    ("archive", False): ARCHIVE_PUBLIC_INDEX,
    ("archive", True):  ARCHIVE_PRIVATE_INDEX,
}


def _partition_four(entries: list[dict]) -> dict[tuple[str, bool], list[dict]]:
    """Bucket entries into (active|archive) × (public|private)."""
    buckets: dict[tuple[str, bool], list[dict]] = {
        ("active",  False): [],
        ("active",  True):  [],
        ("archive", False): [],
        ("archive", True):  [],
    }
    for e in entries:
        bucket = "archive" if e["is_archived"] else "active"
        buckets[(bucket, bool(e["is_private"]))].append(e)
    return buckets


def _write_four_indices(
    entries: list[dict],
    *,
    with_used_by: bool,
    with_line_numbers: bool,
) -> None:
    """Render and write all four index files. Mkdir for the archive subdir."""
    ARCHIVE_PUBLIC_INDEX.parent.mkdir(parents=True, exist_ok=True)
    buckets = _partition_four(entries)
    counts: dict[tuple[str, bool], int] = {}
    for key, bucket_entries in buckets.items():
        path = _INDEX_PATHS[key]
        path.write_text(render_index(
            bucket_entries,
            title=_INDEX_TITLES[key],
            description=_INDEX_DESCRIPTIONS[key],
            with_used_by=with_used_by,
            with_line_numbers=with_line_numbers,
        ))
        counts[key] = len(bucket_entries)
    for key, count in counts.items():
        path = _INDEX_PATHS[key]
        print(f"Wrote {path.relative_to(REPO_ROOT)} ({count} entries)")


def cmd_rewrite(args: argparse.Namespace) -> None:
    existing, hints = load_existing_index()
    source = parse_all_lean()
    if args.include_new:
        existing = existing + discover_new_entries(existing, source)
    section_to_path = build_section_path_map(existing, source, hints)
    entries = assemble_entries(existing, source, section_to_path)

    if args.with_used_by:
        used_by_map = compute_used_by_map(source)
        index_names = {e["name"] for e in entries}
        for e in entries:
            if e["is_simp"]:
                e["new_used_by"] = []  # ignore for simp
            else:
                refs = used_by_map.get(e["name"], set())
                e["new_used_by"] = sorted(r for r in refs if r in index_names)
    else:
        for e in entries:
            e["new_used_by"] = []

    _write_four_indices(
        entries,
        with_used_by=args.with_used_by,
        with_line_numbers=args.with_line_numbers,
    )


# ---------------------------------------------------------------------------
# `split` subcommand
# ---------------------------------------------------------------------------
def cmd_split(args: argparse.Namespace) -> None:
    """One-shot migration from the legacy single-file `TheoremIndex.md` to
    the four-file active/archive × public/private layout."""
    if not SINGLE_INDEX.exists():
        sys.exit(f"{SINGLE_INDEX} does not exist; nothing to split.")

    existing, hints = parse_index_file(SINGLE_INDEX)
    source = parse_all_lean()
    section_to_path = build_section_path_map(existing, source, hints)
    entries = assemble_entries(existing, source, section_to_path)

    if args.with_used_by:
        used_by_map = compute_used_by_map(source)
        index_names = {e["name"] for e in entries}
        for e in entries:
            if e["is_simp"]:
                e["new_used_by"] = []
            else:
                refs = used_by_map.get(e["name"], set())
                e["new_used_by"] = sorted(r for r in refs if r in index_names)
    else:
        for e in entries:
            e["new_used_by"] = []

    _write_four_indices(
        entries,
        with_used_by=args.with_used_by,
        with_line_numbers=args.with_line_numbers,
    )
    SINGLE_INDEX.unlink()


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    sp = parser.add_subparsers(dest="command", required=True)

    sp.add_parser("check", help="Sanity-check 'Used By' against source.").set_defaults(func=cmd_check)

    p_rw = sp.add_parser("rewrite", help="Regenerate the index file(s).")
    p_rw.add_argument("--with-used-by", action="store_true",
                      help="Include the 'Used By' column (skipped for `@[simp]`).")
    p_rw.add_argument("--with-line-numbers", action="store_true",
                      help="Include the 'Line' column (source line number).")
    p_rw.add_argument("--include-new", action="store_true",
                      help="Add placeholder entries for source declarations "
                           "not yet in the index (description/notes = '—').")
    p_rw.set_defaults(func=cmd_rewrite)

    p_sp = sp.add_parser("split",
                         help="One-shot: split TheoremIndex.md into Public + Private.")
    p_sp.add_argument("--with-used-by", action="store_true")
    p_sp.add_argument("--with-line-numbers", action="store_true")
    p_sp.set_defaults(func=cmd_split)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
