#!/usr/bin/env python3
"""Sanity check the 'Used By' column in TheoremIndex.md.

Algorithm:
  1. Parse the markdown table to get  name -> declared_used_by_list.
  2. Parse every .lean file under FullCorrectness/, extracting
     (declaration_name, body_text)  pairs (body = source text from the
     declaration line until the next declaration line).
  3. For each indexed theorem A, scan all OTHER bodies for references
     to A's identifier (using its last-segment as a whole word so that
     `permute_adj`, `AdjMatrix.permute_adj`, and `G.permute_adj` all match).
  4. Compare actual_used_by[A] against declared_used_by[A].

The output prioritises **false positives** — entries that are listed in
'Used By' but don't appear in any source body — since those are most
likely to indicate stale/incorrect index entries. 'Missing' entries are
also reported but tend to over-report when a declaration is mentioned
only in another theorem's *type signature* rather than its proof body.

Limitations:
  - Cannot detect implicit uses (typeclass synthesis, simp lemmas,
    elaboration-time identifiers).
  - Names with spaces or parens (typeclass instance descriptors like
    `Decidable (σ ∈ G.Aut)`) have no Lean identifier; skipped.
  - When two source declarations share the same last segment we fall
    back to requiring the full qualified name, which loses dot-method
    references (`G.permute σ` → can't tell which `permute`).
"""
from __future__ import annotations

import re
import sys
from collections import defaultdict
from pathlib import Path

# Resolve paths relative to the repo root (parent of `scripts/`).
REPO_ROOT = Path(__file__).resolve().parent.parent
ROOT = REPO_ROOT / "GraphCanonizationProofs"
INDEX = ROOT / "TheoremIndex.md"
LEAN_ROOT = ROOT / "FullCorrectness"

# Names auto-generated by attributes/structures rather than written as
# explicit declarations. Treated as referenceable but having no body.
AUTOGENERATED = {
    "AdjMatrix.ext",          # @[ext] on `structure AdjMatrix`
}


# ---------------------------------------------------------------------------
# Index parser
# ---------------------------------------------------------------------------
def parse_index() -> dict[str, list[str]]:
    entries: dict[str, list[str]] = {}
    for line in INDEX.read_text().splitlines():
        m = re.match(r"^\|\s*`([^`]+)`\s*\|\s*(.*?)\s*\|", line)
        if not m:
            continue
        name = m.group(1).strip()
        used_by_raw = m.group(2).strip()
        if used_by_raw in ("—", "-", ""):
            used_by: list[str] = []
        else:
            used_by = [
                x.strip().strip("`")
                for x in used_by_raw.split(",")
                if x.strip().strip("`")
            ]
        entries[name] = used_by
    return entries


# ---------------------------------------------------------------------------
# Lean parser
# ---------------------------------------------------------------------------
# A declaration line may be preceded on the SAME LINE by `@[...]` attribute
# blocks. Names may contain unicode word chars, dots, and `!`.
DECL_RE = re.compile(
    r"^\s*"
    r"(?:@\[[^\]]*\]\s*)*"  # any number of inline attributes
    r"(?:private\s+|protected\s+|noncomputable\s+|partial\s+|unsafe\s+)*"
    r"(theorem|lemma|def|instance|abbrev|structure|class|inductive)"
    r"\s+([^\s:({\[]+)",  # name = anything until whitespace/colon/paren/brace/bracket
    re.UNICODE,
)


def parse_lean_file(path: Path) -> list[tuple[str, str]]:
    """Return list of (name_in_source, body_text) declarations."""
    text = path.read_text()
    lines = text.split("\n")
    decls: list[tuple[int, str]] = []
    in_block_comment = 0
    for i, line in enumerate(lines):
        # Track block comments crudely; ignores nested edge cases inside strings.
        opens = line.count("/-")
        closes = line.count("-/")
        was_in = in_block_comment > 0
        in_block_comment = max(0, in_block_comment + opens - closes)
        if was_in:
            continue
        m = DECL_RE.match(line)
        if not m:
            continue
        name = m.group(2)
        # Filter out names that look like operator/notation (start with non-letter/underscore).
        if not (name[0].isalpha() or name[0] == "_"):
            continue
        decls.append((i, name))
    results: list[tuple[str, str]] = []
    for j, (line_idx, name) in enumerate(decls):
        end_line = decls[j + 1][0] if j + 1 < len(decls) else len(lines)
        body = "\n".join(lines[line_idx:end_line])
        results.append((name, body))
    return results


# ---------------------------------------------------------------------------
# Reference detection
# ---------------------------------------------------------------------------
# Pre-strip block comments and line comments so references inside doc
# strings / `--` comments don't count.
def strip_comments(body: str) -> str:
    # Strip block comments  /- ... -/   (non-nested approximation).
    body = re.sub(r"/-[\s\S]*?-/", "", body)
    # Strip line comments `--` to end of line.
    body = re.sub(r"--[^\n]*", "", body)
    return body


def main() -> None:
    index = parse_index()

    all_decls: list[tuple[str, str, Path]] = []
    for path in sorted(LEAN_ROOT.rglob("*.lean")):
        for name, body in parse_lean_file(path):
            all_decls.append((name, strip_comments(body), path))

    print(f"Loaded {len(index)} indexed entries from TheoremIndex.md")
    print(f"Loaded {len(all_decls)} declarations from Lean source files\n")

    last_seg_count: dict[str, int] = defaultdict(int)
    for name, _, _ in all_decls:
        last_seg_count[name.split(".")[-1]] += 1

    source_names = {name for name, _, _ in all_decls} | AUTOGENERATED
    not_found_in_source = sorted(
        a for a in index
        if a not in source_names and " " not in a and "(" not in a
    )

    skipped: list[str] = []
    ambiguous: list[str] = []
    actual_used_by: dict[str, set[str]] = defaultdict(set)
    possible_users: dict[str, set[str]] = defaultdict(set)

    for A in index:
        if " " in A or "(" in A:
            skipped.append(A)
            continue

        last_seg = A.split(".")[-1]
        is_ambig = last_seg_count[last_seg] > 1
        if is_ambig:
            ambiguous.append(A)
            # Definite pattern: the fully qualified name appears literally.
            definite_pat = re.compile(rf"(?<![\w.]){re.escape(A)}(?!\w)")
            # Possible pattern: the bare segment as a qualified suffix
            #   (`.foo` after a word char). Could be A or another `.foo`.
            possible_pat = re.compile(rf"(?:(?<=[\w]))\.{re.escape(last_seg)}\b")
        else:
            definite_pat = re.compile(rf"\b{re.escape(last_seg)}\b")
            possible_pat = None

        for B_name, B_body, _ in all_decls:
            if B_name == A:
                continue
            if definite_pat.search(B_body):
                actual_used_by[A].add(B_name)
            elif possible_pat is not None and possible_pat.search(B_body):
                possible_users[A].add(B_name)

    # Categorise results
    real_disc: list[tuple[str, list[str], list[str], list[str]]] = []
    only_unindexed_users: list[tuple[str, list[str]]] = []

    for A in sorted(index):
        if A in skipped:
            continue
        declared = set(index[A])
        actual = actual_used_by.get(A, set())
        possible = possible_users.get(A, set())  # ambiguous matches
        # Treat possible as "could be a real user" — exclude from false-positive list.
        actual_or_possible = actual | possible
        actual_in_idx = {n for n in actual if n in index}
        actual_or_possible_in_idx = {n for n in actual_or_possible if n in index}
        actual_unindexed = sorted(n for n in actual if n not in index)

        # Only flag declared entries that appear nowhere — even ambiguously.
        # And exclude typeclass-instance descriptors (we can't grep for them).
        false_pos = sorted(
            x for x in declared - actual_or_possible_in_idx
            if " " not in x and "(" not in x
        )
        missing = sorted(actual_in_idx - declared)

        if false_pos or missing:
            real_disc.append((A, false_pos, missing, actual_unindexed))
        elif actual_unindexed:
            only_unindexed_users.append((A, actual_unindexed))

    # ---- Print ----
    if skipped:
        print(f"Skipped {len(skipped)} entries with no Lean identifier "
              f"(typeclass instance descriptors)")
        print()

    if not_found_in_source:
        print(f"Indexed names with no matching source declaration "
              f"({len(not_found_in_source)}):")
        for n in not_found_in_source:
            print(f"    {n}")
        print()

    if ambiguous:
        print(f"{len(ambiguous)} indexed names share their last-segment with "
              "another declaration — matched by full qualified name only "
              "(may miss dot-method-call references):")
        for a in ambiguous:
            print(f"    {a}")
        print()

    # Split discrepancies into two reports for readability.
    fp_only = [d for d in real_disc if d[1] and not d[2]]
    miss_only = [d for d in real_disc if d[2] and not d[1]]
    both = [d for d in real_disc if d[1] and d[2]]

    print("================================================================")
    print(f" REPORT 1: {len(fp_only) + len(both)} entries with FALSE POSITIVES")
    print(" (declared 'Used By' entries that do NOT appear in source bodies)")
    print("================================================================\n")
    for A, fps, missing, _ in fp_only + both:
        print(f"--- {A} ---")
        for x in fps:
            print(f"      {x}")
        print()

    print("\n================================================================")
    print(f" REPORT 2: {len(miss_only) + len(both)} entries with MISSING REFERENCES")
    print(" (referenced in source but absent from the 'Used By' column)")
    print(" Note: many will be type-signature mentions, not proof uses.")
    print("================================================================\n")
    for A, _, missing, _ in miss_only + both:
        print(f"--- {A} ---")
        for x in missing:
            print(f"      {x}")
        print()


if __name__ == "__main__":
    main()
