#!/usr/bin/env python3
"""Maintenance tool for the GraphCanonizationProofs theorem index.

Subcommands:
  check                Sanity-check the 'Used By' column against the source.
  rewrite              Regenerate the index file(s), preserving description /
                       notes and emitting a chosen set of optional columns.
  split                One-shot: split TheoremIndex.md into PublicTheoremIndex.md
                       and PrivateTheoremIndex.md, grouped by source file path.

Optional columns (flags on `rewrite` / `split`):
  --with-used-by       Recompute and include the 'Used By' column. For
                       `@[simp]` theorems this column is left empty since they
                       are usually applied implicitly via the `simp` tactic.
  --with-line-numbers  Include a 'Line' column with the source line number.

Discovery (flag on `rewrite`):
  --include-new        Append placeholder entries for source declarations not
                       yet in the index. Use after adding new lemmas / new
                       files (e.g. ChainDescent.lean) so they appear in the
                       regenerated index for description-filling.

The rewrite command auto-detects whether to operate on a single index
(`TheoremIndex.md`) or the split layout (`PublicTheoremIndex.md` +
`PrivateTheoremIndex.md`), based on which files exist on disk.

Source-scan scope: all `.lean` files under `GraphCanonizationProofs/`,
excluding the `.lake/` build / package cache. Files under `Archive/V4/` are
included; their section headers in the regenerated index use the full path
(e.g. `## Archive/V4/FullCorrectness/Basic.lean`).
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

# ---------------------------------------------------------------------------
# Repo / file layout
# ---------------------------------------------------------------------------
REPO_ROOT = Path(__file__).resolve().parent.parent
ROOT = REPO_ROOT / "GraphCanonizationProofs"

SINGLE_INDEX = ROOT / "TheoremIndex.md"
PUBLIC_INDEX = ROOT / "PublicTheoremIndex.md"
PRIVATE_INDEX = ROOT / "PrivateTheoremIndex.md"

# Names auto-generated by attributes/structures rather than written as
# explicit declarations (e.g. `@[ext]` on a structure synthesises `<S>.ext`).
# Maps the auto-generated name to the source file where its origin sits
# (relative to ROOT).
AUTOGENERATED: dict[str, str] = {
    "AdjMatrix.ext": "Archive/V4/FullCorrectness/Basic.lean",
}

# Directory components excluded from the source scan — build artefacts and
# package caches we don't want to walk.
EXCLUDED_DIRS = {".lake"}


# ---------------------------------------------------------------------------
# Lean source parser
# ---------------------------------------------------------------------------
DECL_RE = re.compile(
    r"^\s*"
    r"(?:@\[[^\]]*\]\s*)*"
    r"(?:private\s+|protected\s+|noncomputable\s+|partial\s+|unsafe\s+)*"
    r"(theorem|lemma|def|instance|abbrev|structure|class|inductive)"
    r"\s+([^\s:({\[]+)",
    re.UNICODE,
)
DECL_LINE_RE = re.compile(
    r"^\s*"
    r"((?:@\[[^\]]*\]\s*)*)"
    r"((?:private\s+|protected\s+|noncomputable\s+|partial\s+|unsafe\s+)*)"
    r"(theorem|lemma|def|instance|abbrev|structure|class|inductive)"
    r"\s+([^\s:({\[]+)",
    re.UNICODE,
)


def strip_comments(body: str) -> str:
    """Strip Lean block (nesting-aware) and line comments."""
    out: list[str] = []
    i, n, depth = 0, len(body), 0
    while i < n:
        two = body[i:i + 2]
        if two == "/-":
            depth += 1
            i += 2
        elif two == "-/" and depth > 0:
            depth -= 1
            i += 2
        elif depth > 0:
            i += 1
        elif two == "--":
            while i < n and body[i] != "\n":
                i += 1
        else:
            out.append(body[i])
            i += 1
    return "".join(out)


def parse_lean_file(path: Path) -> list[dict]:
    """Return list of declarations: {name, line, is_private, is_simp, body}."""
    text = path.read_text()
    lines = text.split("\n")

    # First pass: find declarations, skipping any inside block comments.
    decls: list[dict] = []
    in_block_comment = 0
    for i, line in enumerate(lines):
        opens = line.count("/-")
        closes = line.count("-/")
        was_in = in_block_comment > 0
        in_block_comment = max(0, in_block_comment + opens - closes)
        if was_in:
            continue
        m = DECL_LINE_RE.match(line)
        if not m:
            continue
        attrs, modifiers, _kind, name = m.groups()
        if not (name[0].isalpha() or name[0] == "_"):
            continue
        decls.append({
            "name": name,
            "line": i + 1,           # 1-indexed
            "_line_idx": i,
            "is_private": bool(re.search(r"\bprivate\b", modifiers)),
            "is_simp": "@[simp" in (attrs or ""),
        })

    for j, d in enumerate(decls):
        end_idx = decls[j + 1]["_line_idx"] if j + 1 < len(decls) else len(lines)
        d["body"] = "\n".join(lines[d["_line_idx"]:end_idx])
        del d["_line_idx"]
    return decls


def _iter_lean_files() -> list[Path]:
    """All .lean files under ROOT, skipping `.lake/` build/package trees.

    Era-agnostic: scans both active locations (e.g. `ChainDescent.lean`) and
    archived ones (e.g. `Archive/V4/FullCorrectness/...`).
    """
    out: list[Path] = []
    for path in ROOT.rglob("*.lean"):
        rel = path.relative_to(ROOT)
        if any(part in EXCLUDED_DIRS for part in rel.parts):
            continue
        out.append(path)
    return sorted(out)


def parse_all_lean() -> dict[str, dict]:
    """name -> {path, line, is_private, is_simp, body, stripped_body}."""
    out: dict[str, dict] = {}
    for path in _iter_lean_files():
        for d in parse_lean_file(path):
            d["path"] = path.relative_to(ROOT)
            d["stripped_body"] = strip_comments(d["body"])
            out[d["name"]] = d
    return out


# ---------------------------------------------------------------------------
# Markdown index parser
# ---------------------------------------------------------------------------
ROW_RE = re.compile(r"^\|\s*(.*?)\s*\|\s*$")
SECTION_RE = re.compile(r"^##\s+(.+?)\s*$")


def split_row(line: str) -> list[str] | None:
    if not line.startswith("|") or not line.rstrip().endswith("|"):
        return None
    inner = line.rstrip()[1:-1]
    return [c.strip() for c in inner.split("|")]


def parse_index_file(path: Path) -> tuple[list[dict], dict[str, str]]:
    """Returns (entries, section_to_path_hint).

    Each entry is a dict {name, used_by[list], description, notes, section}.
    `section_to_path_hint` is best-effort: if a section header looks like
    `path/to/file.lean`, it maps the section name to that path string.
    """
    entries: list[dict] = []
    section: str | None = None
    section_path_hint: dict[str, str] = {}
    if not path.exists():
        return [], {}
    for line in path.read_text().splitlines():
        m_sec = SECTION_RE.match(line)
        if m_sec:
            section = m_sec.group(1).strip()
            if section.endswith(".lean"):
                section_path_hint[section] = section
            continue
        cells = split_row(line)
        if cells is None:
            continue
        # Header / separator rows: skip them.
        if not cells or cells[0].strip("`") in ("Name", "") or set("".join(cells).replace(" ", "")) <= set("-"):
            continue
        if not cells[0].startswith("`"):
            continue
        name = cells[0].strip().strip("`").strip()
        # Locate description / notes / used_by columns by header heuristic:
        # rows have variable column counts depending on file flavour. We
        # always take the LAST two cells as (description, notes).
        if len(cells) < 3:
            continue
        notes = cells[-1]
        description = cells[-2]
        # Any in-between cells are optional columns (Used By, Line).
        # We only care about Used By here; skip Line if present.
        middle = cells[1:-2]
        used_by_raw = ""
        for c in middle:
            # Skip if it looks like a pure integer (Line column).
            if c.strip().isdigit():
                continue
            used_by_raw = c
            break
        used_by = parse_used_by_cell(used_by_raw)
        entries.append({
            "name": name,
            "used_by": used_by,
            "description": description,
            "notes": notes,
            "section": section,
        })
    return entries, section_path_hint


def parse_used_by_cell(cell: str) -> list[str]:
    cell = cell.strip()
    if cell in ("—", "-", ""):
        return []
    return [
        x.strip().strip("`")
        for x in cell.split(",")
        if x.strip().strip("`")
    ]


def detect_layout() -> str:
    """'split' if both split files exist, else 'single'."""
    if PUBLIC_INDEX.exists() and PRIVATE_INDEX.exists():
        return "split"
    return "single"


def load_existing_index() -> tuple[list[dict], dict[str, str]]:
    """Read whichever index files exist and merge them."""
    layout = detect_layout()
    if layout == "split":
        e1, h1 = parse_index_file(PUBLIC_INDEX)
        e2, h2 = parse_index_file(PRIVATE_INDEX)
        return e1 + e2, {**h1, **h2}
    return parse_index_file(SINGLE_INDEX)


# ---------------------------------------------------------------------------
# Used-By computation
# ---------------------------------------------------------------------------
def compute_used_by_map(source: dict[str, dict]) -> dict[str, set[str]]:
    """For each declaration A in `source`, find all other declarations B whose
    body textually references A (last-segment-as-word matching, with fallback
    to qualified-name when the last segment is ambiguous)."""
    last_seg_count: dict[str, int] = defaultdict(int)
    for name in source:
        last_seg_count[name.split(".")[-1]] += 1

    actual: dict[str, set[str]] = defaultdict(set)
    possible: dict[str, set[str]] = defaultdict(set)

    decls = list(source.items())
    for A, A_info in decls:
        last_seg = A.split(".")[-1]
        is_ambig = last_seg_count[last_seg] > 1
        if is_ambig:
            definite_pat = re.compile(rf"(?<![\w.]){re.escape(A)}(?!\w)")
            possible_pat: re.Pattern | None = re.compile(
                rf"(?:(?<=[\w]))\.{re.escape(last_seg)}\b"
            )
        else:
            definite_pat = re.compile(rf"\b{re.escape(last_seg)}\b")
            possible_pat = None
        for B, B_info in decls:
            if B == A:
                continue
            body = B_info["stripped_body"]
            if definite_pat.search(body):
                actual[A].add(B)
            elif possible_pat is not None and possible_pat.search(body):
                possible[A].add(B)
    # Stitch: also include possible-only matches as actual users (we err on
    # the side of recording references; the check command flags ambiguity).
    for A, users in possible.items():
        actual[A] |= users
    return actual


# ---------------------------------------------------------------------------
# `check` subcommand  (the original behaviour)
# ---------------------------------------------------------------------------
def cmd_check(_args: argparse.Namespace) -> None:
    entries, _ = load_existing_index()
    declared_used_by = {e["name"]: set(e["used_by"]) for e in entries}
    index_names = {e["name"] for e in entries}
    source = parse_all_lean()

    print(f"Loaded {len(entries)} indexed entries from {detect_layout()} layout")
    print(f"Loaded {len(source)} declarations from Lean source files\n")

    last_seg_count: dict[str, int] = defaultdict(int)
    for name in source:
        last_seg_count[name.split(".")[-1]] += 1

    source_names = set(source) | set(AUTOGENERATED)
    not_found_in_source = sorted(
        a for a in index_names
        if a not in source_names and " " not in a and "(" not in a
    )

    skipped: list[str] = []
    ambiguous: list[str] = []
    actual: dict[str, set[str]] = defaultdict(set)
    possible: dict[str, set[str]] = defaultdict(set)

    for A in index_names:
        if " " in A or "(" in A:
            skipped.append(A)
            continue
        last_seg = A.split(".")[-1]
        is_ambig = last_seg_count[last_seg] > 1
        if is_ambig:
            ambiguous.append(A)
            definite_pat = re.compile(rf"(?<![\w.]){re.escape(A)}(?!\w)")
            possible_pat: re.Pattern | None = re.compile(
                rf"(?:(?<=[\w]))\.{re.escape(last_seg)}\b"
            )
        else:
            definite_pat = re.compile(rf"\b{re.escape(last_seg)}\b")
            possible_pat = None
        for B, info in source.items():
            if B == A:
                continue
            body = info["stripped_body"]
            if definite_pat.search(body):
                actual[A].add(B)
            elif possible_pat is not None and possible_pat.search(body):
                possible[A].add(B)

    real_disc: list[tuple[str, list[str], list[str]]] = []
    for A in sorted(index_names):
        if A in skipped:
            continue
        declared = declared_used_by[A]
        actual_in_idx = {n for n in actual[A] if n in index_names}
        all_in_idx = actual_in_idx | {n for n in possible[A] if n in index_names}
        false_pos = sorted(
            x for x in declared - all_in_idx
            if " " not in x and "(" not in x
        )
        missing = sorted(actual_in_idx - declared)
        if false_pos or missing:
            real_disc.append((A, false_pos, missing))

    if skipped:
        print(f"Skipped {len(skipped)} typeclass-instance descriptors\n")
    if not_found_in_source:
        print(f"Indexed names with no source declaration ({len(not_found_in_source)}):")
        for n in not_found_in_source:
            print(f"    {n}")
        print()
    if ambiguous:
        print(f"{len(ambiguous)} indexed names share their last segment "
              "(matched only by full qualified name):")
        for a in ambiguous:
            print(f"    {a}")
        print()

    fp_only = [d for d in real_disc if d[1] and not d[2]]
    miss_only = [d for d in real_disc if d[2] and not d[1]]
    both = [d for d in real_disc if d[1] and d[2]]

    print("=" * 64)
    print(f" REPORT 1: {len(fp_only) + len(both)} entries with FALSE POSITIVES")
    print(" (declared 'Used By' entries with no textual mention in source)")
    print("=" * 64 + "\n")
    for A, fps, _ in fp_only + both:
        print(f"--- {A} ---")
        for x in fps:
            print(f"      {x}")
        print()

    print("\n" + "=" * 64)
    print(f" REPORT 2: {len(miss_only) + len(both)} entries with MISSING REFERENCES")
    print(" (textual mentions in source absent from 'Used By')")
    print("=" * 64 + "\n")
    for A, _, missing in miss_only + both:
        print(f"--- {A} ---")
        for x in missing:
            print(f"      {x}")
        print()


# ---------------------------------------------------------------------------
# `rewrite` subcommand
# ---------------------------------------------------------------------------
def build_section_path_map(
    entries: list[dict],
    source: dict[str, dict],
    section_path_hints: dict[str, str],
) -> dict[str, str]:
    """Map an index section header to a source file path.

    Used to assign typeclass-instance entries (which have no Lean identifier)
    to the same file as the named theorems they sit alongside.

    Resolution order:
      1. Best-by-count from source-resolved entries in the section.
      2. The section-header hint (`## path/to/file.lean`) **only if** the
         hinted file still exists on disk. Stale hints from before an
         archival move are dropped — the inferred best path wins.
    """
    section_to_path: dict[str, str] = {}
    counts: dict[str, dict[str, int]] = defaultdict(lambda: defaultdict(int))
    for e in entries:
        sec = e["section"]
        if sec is None or e["name"] not in source:
            continue
        path_str = str(source[e["name"]]["path"])
        counts[sec][path_str] += 1
    for sec, dist in counts.items():
        # Pick the file path with the most entries in that section.
        best = max(dist.items(), key=lambda kv: kv[1])[0]
        section_to_path[sec] = best
    for sec, hint in section_path_hints.items():
        if (ROOT / hint).exists() and sec not in section_to_path:
            section_to_path[sec] = hint
    return section_to_path


def assemble_entries(
    existing: list[dict],
    source: dict[str, dict],
    section_to_path: dict[str, str],
) -> list[dict]:
    """Produce a list of fully-resolved entries with path/line/private/simp."""
    out: list[dict] = []
    for e in existing:
        name = e["name"]
        if name in source:
            info = source[name]
            path_str = str(info["path"])
            line = info["line"]
            is_private = info["is_private"] or "private" in e["notes"].lower()
            is_simp = info["is_simp"] or "@[simp]" in e["notes"]
        else:
            path_str = (
                AUTOGENERATED.get(name)
                or section_to_path.get(e["section"], "")
            )
            line = None
            is_private = "private" in e["notes"].lower()
            is_simp = "@[simp]" in e["notes"]
        out.append({
            **e,
            "path": path_str,
            "line": line,
            "is_private": is_private,
            "is_simp": is_simp,
        })
    return out


def render_used_by(items: list[str]) -> str:
    if not items:
        return "—"
    return ", ".join(f"`{x}`" for x in sorted(set(items), key=lambda s: s.lower()))


def render_table(
    rows: list[dict],
    *,
    with_used_by: bool,
    with_line_numbers: bool,
) -> list[str]:
    headers = ["Name"]
    if with_used_by:
        headers.append("Used By")
    if with_line_numbers:
        headers.append("Line")
    headers += ["Description", "Notes"]

    out: list[str] = []
    out.append("| " + " | ".join(headers) + " |")
    out.append("|" + "|".join("-" * (len(h) + 2) for h in headers) + "|")
    for r in rows:
        cells = [f"`{r['name']}`"]
        if with_used_by:
            cells.append(render_used_by(r["new_used_by"]))
        if with_line_numbers:
            cells.append(str(r["line"]) if r["line"] is not None else "—")
        cells.append(r["description"] or "—")
        cells.append(r["notes"] or "—")
        out.append("| " + " | ".join(cells) + " |")
    return out


def render_index(
    entries: list[dict],
    *,
    title: str,
    description: str,
    with_used_by: bool,
    with_line_numbers: bool,
) -> str:
    # Group by path; preserve existing path order based on first appearance.
    path_order: list[str] = []
    by_path: dict[str, list[dict]] = defaultdict(list)
    for e in entries:
        if e["path"] not in by_path:
            path_order.append(e["path"])
        by_path[e["path"]].append(e)

    # Within a section, sort by line number (None goes last).
    for p in by_path:
        by_path[p].sort(key=lambda r: (r["line"] is None, r["line"] or 0))

    legend = ["## Legend", ""]
    if with_used_by:
        legend.append(
            "- **Used By**: Theorems/definitions that directly reference this one. "
            "Empty for `@[simp]` theorems (used implicitly via the `simp` tactic)."
        )
    if with_line_numbers:
        legend.append("- **Line**: Source line number of the declaration.")
    legend.extend([
        "- **Description**: A short description of what the theorem proves.",
        "- **Notes**: `@[simp]` / `@[ext]` attributes, `private`, instances, "
        "or other special properties.",
        "",
    ])

    out: list[str] = [f"# {title}", "", description, ""]
    out.extend(legend)
    for p in path_order:
        if not p:
            continue
        out.append(f"## {p}")
        out.append("")
        out.extend(render_table(
            by_path[p],
            with_used_by=with_used_by,
            with_line_numbers=with_line_numbers,
        ))
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def discover_new_entries(
    existing: list[dict],
    source: dict[str, dict],
) -> list[dict]:
    """Source declarations not yet in the index, as fresh placeholder entries.

    Each new entry gets `description = "—"` and `notes = "—"` (per the index
    convention for empty cells). They show up in the regenerated index so a
    human can fill them in incrementally without losing newly-added lemmas.
    """
    already = {e["name"] for e in existing}
    new_entries: list[dict] = []
    for name, info in source.items():
        if name in already:
            continue
        new_entries.append({
            "name": name,
            "used_by": [],
            "description": "—",
            "notes": "—",
            "section": str(info["path"]),
        })
    return new_entries


def cmd_rewrite(args: argparse.Namespace) -> None:
    existing, hints = load_existing_index()
    source = parse_all_lean()
    if args.include_new:
        existing = existing + discover_new_entries(existing, source)
    section_to_path = build_section_path_map(existing, source, hints)
    entries = assemble_entries(existing, source, section_to_path)

    if args.with_used_by:
        used_by_map = compute_used_by_map(source)
        index_names = {e["name"] for e in entries}
        for e in entries:
            if e["is_simp"]:
                e["new_used_by"] = []  # ignore for simp
            else:
                refs = used_by_map.get(e["name"], set())
                e["new_used_by"] = sorted(r for r in refs if r in index_names)
    else:
        for e in entries:
            e["new_used_by"] = []

    layout = detect_layout()
    if layout == "split":
        public_entries = [e for e in entries if not e["is_private"]]
        private_entries = [e for e in entries if e["is_private"]]
        PUBLIC_INDEX.write_text(render_index(
            public_entries,
            title="Public Theorem Index — GraphCanonizationProofs",
            description=(
                "Index of public Lean theorems, lemmas, and definitions in the "
                "GraphCanonizationProofs project, grouped by source file path."
            ),
            with_used_by=args.with_used_by,
            with_line_numbers=args.with_line_numbers,
        ))
        PRIVATE_INDEX.write_text(render_index(
            private_entries,
            title="Private Theorem Index — GraphCanonizationProofs",
            description=(
                "Index of private Lean theorems, lemmas, and definitions in the "
                "GraphCanonizationProofs project, grouped by source file path."
            ),
            with_used_by=args.with_used_by,
            with_line_numbers=args.with_line_numbers,
        ))
        print(f"Wrote {PUBLIC_INDEX.relative_to(REPO_ROOT)} "
              f"({len(public_entries)} entries) "
              f"and {PRIVATE_INDEX.relative_to(REPO_ROOT)} "
              f"({len(private_entries)} entries)")
    else:
        SINGLE_INDEX.write_text(render_index(
            entries,
            title="Lean Theorem Index — GraphCanonizationProofs",
            description=(
                "Index of all Lean theorems, lemmas, and definitions in the "
                "GraphCanonizationProofs project, grouped by source file path."
            ),
            with_used_by=args.with_used_by,
            with_line_numbers=args.with_line_numbers,
        ))
        print(f"Wrote {SINGLE_INDEX.relative_to(REPO_ROOT)} ({len(entries)} entries)")


# ---------------------------------------------------------------------------
# `split` subcommand
# ---------------------------------------------------------------------------
def cmd_split(args: argparse.Namespace) -> None:
    if not SINGLE_INDEX.exists():
        sys.exit(f"{SINGLE_INDEX} does not exist; nothing to split.")

    existing, hints = parse_index_file(SINGLE_INDEX)
    source = parse_all_lean()
    section_to_path = build_section_path_map(existing, source, hints)
    entries = assemble_entries(existing, source, section_to_path)

    if args.with_used_by:
        used_by_map = compute_used_by_map(source)
        index_names = {e["name"] for e in entries}
        for e in entries:
            if e["is_simp"]:
                e["new_used_by"] = []
            else:
                refs = used_by_map.get(e["name"], set())
                e["new_used_by"] = sorted(r for r in refs if r in index_names)
    else:
        for e in entries:
            e["new_used_by"] = []

    public_entries = [e for e in entries if not e["is_private"]]
    private_entries = [e for e in entries if e["is_private"]]

    PUBLIC_INDEX.write_text(render_index(
        public_entries,
        title="Public Theorem Index — GraphCanonizationProofs",
        description=(
            "Index of public Lean theorems, lemmas, and definitions in the "
            "GraphCanonizationProofs project, grouped by source file path."
        ),
        with_used_by=args.with_used_by,
        with_line_numbers=args.with_line_numbers,
    ))
    PRIVATE_INDEX.write_text(render_index(
        private_entries,
        title="Private Theorem Index — GraphCanonizationProofs",
        description=(
            "Index of private Lean theorems, lemmas, and definitions in the "
            "GraphCanonizationProofs project, grouped by source file path."
        ),
        with_used_by=args.with_used_by,
        with_line_numbers=args.with_line_numbers,
    ))
    SINGLE_INDEX.unlink()
    print(f"Split {SINGLE_INDEX.name} → "
          f"{PUBLIC_INDEX.name} ({len(public_entries)} entries), "
          f"{PRIVATE_INDEX.name} ({len(private_entries)} entries)")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    sp = parser.add_subparsers(dest="command", required=True)

    sp.add_parser("check", help="Sanity-check 'Used By' against source.").set_defaults(func=cmd_check)

    p_rw = sp.add_parser("rewrite", help="Regenerate the index file(s).")
    p_rw.add_argument("--with-used-by", action="store_true",
                      help="Include the 'Used By' column (skipped for `@[simp]`).")
    p_rw.add_argument("--with-line-numbers", action="store_true",
                      help="Include the 'Line' column (source line number).")
    p_rw.add_argument("--include-new", action="store_true",
                      help="Add placeholder entries for source declarations "
                           "not yet in the index (description/notes = '—').")
    p_rw.set_defaults(func=cmd_rewrite)

    p_sp = sp.add_parser("split",
                         help="One-shot: split TheoremIndex.md into Public + Private.")
    p_sp.add_argument("--with-used-by", action="store_true")
    p_sp.add_argument("--with-line-numbers", action="store_true")
    p_sp.set_defaults(func=cmd_split)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
