import FullCorrectness.Automorphism

/-!
# §2  Bridge lemma: `Isomorphic ↔ ∃ σ, H = G.permute σ`

Bridges the inductive `Isomorphic` relation (generated by `refl`, `swap`, `trans`) to the
extensional "∃ permutation σ, H = G.permute σ" statement. All downstream equivariance
reasoning works through the permutation action rather than walking the constructor tree.
-/

namespace Graph
namespace AdjMatrix

variable {n : Nat}

/-! ## (⟹) direction -/

/--
Every `Isomorphic` witness gives rise to a concrete permutation realizing the relabeling.
Composition order `σ₂ * σ₁` in the `trans` case is forced by the left-action convention
`G.permute (σ * τ) = (G.permute τ).permute σ` (see `permute_mul`).
-/
theorem permute_of_Isomorphic {G H : AdjMatrix n} (h : G ≃ H) :
    ∃ σ : Equiv.Perm (Fin n), H = G.permute σ := by
  induction h with
  | refl G => exact ⟨1, (AdjMatrix.permute_one G).symm⟩
  | swap G v1 v2 =>
      refine ⟨Equiv.swap v1 v2, ?_⟩
      exact swapVertexLabels_eq_permute G v1 v2
  | trans _ _ ih₁ ih₂ =>
      obtain ⟨σ₁, hσ₁⟩ := ih₁
      obtain ⟨σ₂, hσ₂⟩ := ih₂
      refine ⟨σ₂ * σ₁, ?_⟩
      rw [AdjMatrix.permute_mul, ← hσ₁, ← hσ₂]

/-! ## (⟸) direction -/

/--
For every permutation `σ`, `G ≃ G.permute σ`. Proved by induction on a decomposition of
`σ` into transpositions via Mathlib's `Equiv.Perm.swap_induction_on`.
-/
theorem Isomorphic_permute (G : AdjMatrix n) (σ : Equiv.Perm (Fin n)) :
    G ≃ G.permute σ := by
  -- Induction on σ using swap_induction_on. The motive is `P σ := G ≃ G.permute σ`.
  induction σ using Equiv.Perm.swap_induction_on with
  | one =>
      rw [AdjMatrix.permute_one]
      exact Isomorphic.refl G
  | swap_mul f x y hxy ih =>
      -- Goal: G ≃ G.permute (Equiv.swap x y * f).
      -- permute_mul : G.permute (swap x y * f) = (G.permute f).permute (swap x y)
      -- swapVertexLabels_eq_permute bridges back to the inductive swap constructor.
      rw [AdjMatrix.permute_mul, ← swapVertexLabels_eq_permute]
      exact Isomorphic.trans ih (Isomorphic.swap (G.permute f) x y)

/-- Concrete-permutation form of `Isomorphic`: if `H = G.permute σ`, then `G ≃ H`. -/
theorem Isomorphic_of_permute {G H : AdjMatrix n} {σ : Equiv.Perm (Fin n)}
    (h : H = G.permute σ) : G ≃ H := by
  rw [h]
  exact Isomorphic_permute G σ

/-! ## Biconditional -/

/-- The bridge: inductive `Isomorphic` is equivalent to "∃ permutation σ, H = G.permute σ". -/
theorem Isomorphic_iff_exists_permute {G H : AdjMatrix n} :
    G ≃ H ↔ ∃ σ : Equiv.Perm (Fin n), H = G.permute σ :=
  ⟨permute_of_Isomorphic, fun ⟨_, h⟩ => Isomorphic_of_permute h⟩

end AdjMatrix
end Graph
