"""How big must the gauge be to CONTAIN a given difference vector?

The copy set must contain both members of the fusable pair, so the gauge H must
contain d = E(G) /_\ E(G').  H must be S_L-invariant, so H >= the S_L-module
generated by d.  Measure that module for the shapes a falsifier would use.
"""
import itertools, sys

def slots(n): return [(i, j) for i in range(n) for j in range(i + 1, n)]
def perms_bit(n):
    S = slots(n); idx = {s: k for k, s in enumerate(S)}
    return [[idx[tuple(sorted((p[i], p[j])))] for (i, j) in S]
            for p in itertools.permutations(range(n))]
def rref(vs):
    b = {}
    for v in vs:
        while v:
            h = v.bit_length() - 1
            if h in b: v ^= b[h]
            else: b[h] = v; break
    return tuple(sorted(b.values(), reverse=True))
def module_dim(v, perms):
    bits = [i for i in range(v.bit_length()) if (v >> i) & 1]
    orb = set()
    for pm in perms:
        w = 0
        for i in bits: w |= 1 << pm[i]
        orb.add(w)
    return len(rref(orb))

for n in (6, 7, 8):
    S = slots(n); idx = {s: k for k, s in enumerate(S)}; d = len(S); P = perms_bit(n)
    def V(es): 
        m = 0
        for e in es: m |= 1 << idx[tuple(sorted(e))]
        return m
    star = V([(0, j) for j in range(1, n)])
    cases = {
        "one edge (a CFI-style twist)":       V([(0, 1)]),
        "two disjoint edges (a swap)":        V([(0, 1), (2, 3)]),
        "two adjacent edges":                 V([(0, 1), (0, 2)]),
        "a triangle":                         V([(0, 1), (1, 2), (0, 2)]),
        "a 4-cycle":                          V([(0,1),(1,2),(2,3),(0,3)]),
        "a STAR = delta({v}) (switching)":    star,
    }
    print(f"n={n} (edge dim {d}, cut dim {n-1}):")
    for name, v in cases.items():
        k = module_dim(v, P)
        print(f"   {name:34s} -> smallest invariant gauge has dim {k:2d}  (size 2^{k} of 2^{d})")
