#!/usr/bin/env python3
"""HUNT #1 — a NON-SCHURIAN one-point extension, i.e. a 2-WL counterexample to
"CellsAreOrbits + one individualization => orbits".   (2026-07-30)

WHY CAYLEY GRAPHS ARE THE CAPABLE HABITAT (they are NOT covered by the handoff's §3
exclusions, which are about GRR *existence* at 1-WL):

  * Aut(Cay(G,S)) is transitive => the root orbit partition is ONE cell => CAO holds free.
  * The coherent (2-WL) closure of a Cayley graph AT THE ROOT is translation-invariant,
    hence it is a SCHUR RING over G, computable directly on G in O(n^2) per round -- no
    n^3 pair colouring -- via the structure constants
        c_{i,j}(g) = #{(t,u) in P_i x P_j : t*u = g}.
    That is a ~1000x cheaper PRE-FILTER than running 2-WL on the graph.
  * If the S-ring is DISCRETE (all basic sets singletons) the true 2-WL extension is
    discrete too (it is at least as fine) => no counterexample => skip instantly.

  ⚠ MEASURED CORRECTION (2026-07-30): the S-ring is the closure of the ROOT only.  Once e
  is individualized the configuration is NO LONGER translation-invariant, so the real 2-WL
  extension refines STRICTLY PAST the S-ring -- measured over Z4^2, Z8xZ2, Z4xZ2^2, D16,
  SD16, M16, Q16, D8xZ2: S-ring basic sets [1,1,2,4,4,4] -> 2-WL cells [1,1,2,2,2,4,4].
  That is exactly why every non-schurian S-ring found here is still REPAIRED: the
  individualization destroys the homogeneity the blindness rested on.  So the S-ring is a
  sound NECESSARY-condition filter, never the verdict -- stage 3 must run the real 2-WL.

PIPELINE
  1. S-ring filter over many (G, S)                          [cheap, O(n^2)]
  2. survivors: real 2-WL on the graph, individualizing e    [O(n^3) per round]
  3. still non-discrete: EXACT Aut_e (sound machinery) and the mixed-cell verdict

Lagrange note: a cell of size c can only be an orbit if c | |Aut_e|, so a small stabiliser
against a coarse cell is an automatic hit -- no orbit oracle needed.
"""
import sys, random, time
from collections import defaultdict
from itertools import product
sys.path.insert(0, "/workspace/scratchpad")
from probe_cao_cleanroom import wl, individualize, cells, all_isos, orbits, is_perm_aut
from probe_cao_vtcover import iso_exists

LOG = open("/workspace/scratchpad/sring_hunt.log", "w", buffering=1)


def say(*a):
    s = " ".join(str(x) for x in a)
    print(s)
    LOG.write(s + "\n")


# ---------------------------------------------------------------- groups (verified)
def check_group(mul, name):
    n = len(mul)
    assert all(len(r) == n for r in mul), name
    assert all(mul[0][x] == x and mul[x][0] == x for x in range(n)), f"{name}: identity"
    for x in range(n):
        assert sorted(mul[x]) == list(range(n)), f"{name}: not a latin square"
    for x in range(n):
        for y in range(n):
            for z in range(n):
                if mul[mul[x][y]][z] != mul[x][mul[y][z]]:
                    raise AssertionError(f"{name}: not associative")
    return mul


def g_cyclic(m):
    return [[(a + b) % m for b in range(m)] for a in range(m)]


def g_direct(A, B):
    na, nb = len(A), len(B)
    idx = lambda a, b: a * nb + b
    return [[idx(A[a1][a2], B[b1][b2]) for a2 in range(na) for b2 in range(nb)]
            for a1 in range(na) for b1 in range(nb)]


def g_semidirect_cyclic(m, k, order=2):
    """Z_m  x|  Z_order  with the action x -> x^k  (k^order == 1 mod m required)."""
    assert pow(k, order, m) == 1
    els = [(r, s) for s in range(order) for r in range(m)]
    ix = {e: i for i, e in enumerate(els)}
    def mult(e1, e2):
        (r1, s1), (r2, s2) = e1, e2
        return ((r1 + r2 * pow(k, s1, m)) % m, (s1 + s2) % order)
    return [[ix[mult(e1, e2)] for e2 in els] for e1 in els]


def g_dicyclic(m):
    """Dic_m of order 4m: <a,b | a^{2m}=1, b^2=a^m, b a b^-1 = a^-1>."""
    N = 2 * m
    els = [(r, s) for s in range(2) for r in range(N)]
    ix = {e: i for i, e in enumerate(els)}
    def mult(e1, e2):
        (r1, s1), (r2, s2) = e1, e2
        r = (r1 + (r2 if s1 == 0 else -r2)) % N
        s = s1 + s2
        if s >= 2:
            s -= 2
            r = (r + m) % N
        return (r, s)
    return [[ix[mult(e1, e2)] for e2 in els] for e1 in els]


def g_perm(gens, deg):
    """The permutation group generated by `gens` (tuples), as a multiplication table."""
    idp = tuple(range(deg))
    els = {idp}
    frontier = [idp]
    while frontier:
        p = frontier.pop()
        for g in gens:
            q = tuple(g[p[i]] for i in range(deg))
            if q not in els:
                els.add(q)
                frontier.append(q)
    els = sorted(els, key=lambda p: (p != idp, p))
    ix = {e: i for i, e in enumerate(els)}
    return [[ix[tuple(e2[e1[i]] for i in range(deg))] for e2 in els] for e1 in els]


GROUPS = []


def add(name, mul):
    try:
        check_group(mul, name)
    except AssertionError as ex:
        say("  !! BROKEN GROUP SKIPPED:", name, ex)
        return
    GROUPS.append((name, mul))


add("Z8", g_cyclic(8))
add("Z2^3", g_direct(g_direct(g_cyclic(2), g_cyclic(2)), g_cyclic(2)))
add("Z4xZ2", g_direct(g_cyclic(4), g_cyclic(2)))
add("D8", g_semidirect_cyclic(4, 3))
add("Q8", g_dicyclic(2))
add("Z9", g_cyclic(9))
add("Z3^2", g_direct(g_cyclic(3), g_cyclic(3)))
add("Z12", g_cyclic(12))
add("D12", g_semidirect_cyclic(6, 5))
add("Dic3", g_dicyclic(3))
add("Z6xZ2", g_direct(g_cyclic(6), g_cyclic(2)))
add("A4", g_perm([(1, 2, 0, 3), (0, 2, 3, 1)], 4))
add("Z16", g_cyclic(16))
add("Z2^4", g_direct(g_direct(g_cyclic(2), g_cyclic(2)), g_direct(g_cyclic(2), g_cyclic(2))))
add("Z4^2", g_direct(g_cyclic(4), g_cyclic(4)))
add("Z8xZ2", g_direct(g_cyclic(8), g_cyclic(2)))
add("Z4xZ2^2", g_direct(g_cyclic(4), g_direct(g_cyclic(2), g_cyclic(2))))
add("D16", g_semidirect_cyclic(8, 7))
add("SD16", g_semidirect_cyclic(8, 3))
add("M16", g_semidirect_cyclic(8, 5))
add("Q16", g_dicyclic(4))
add("D8xZ2", g_direct(g_semidirect_cyclic(4, 3), g_cyclic(2)))
add("Q8xZ2", g_direct(g_dicyclic(2), g_cyclic(2)))
add("Z18", g_cyclic(18))
add("Z3xZ6", g_direct(g_cyclic(3), g_cyclic(6)))
add("Z20", g_cyclic(20))
add("Z2^2xZ5", g_direct(g_direct(g_cyclic(2), g_cyclic(2)), g_cyclic(5)))
add("Z24", g_cyclic(24))
add("Z2^3xZ3", g_direct(g_direct(g_direct(g_cyclic(2), g_cyclic(2)), g_cyclic(2)), g_cyclic(3)))
add("Z4xZ6", g_direct(g_cyclic(4), g_cyclic(6)))
add("SL(2,3)", g_perm([(1, 2, 0, 3), (0, 2, 3, 1)], 4) if False else g_dicyclic(6))
add("Z27", g_cyclic(27))
add("Z3^3", g_direct(g_direct(g_cyclic(3), g_cyclic(3)), g_cyclic(3)))
add("Z9xZ3", g_direct(g_cyclic(9), g_cyclic(3)))
add("Z2^5", g_direct(g_direct(g_direct(g_cyclic(2), g_cyclic(2)),
                             g_direct(g_cyclic(2), g_cyclic(2))), g_cyclic(2)))
add("Z4^2xZ2", g_direct(g_direct(g_cyclic(4), g_cyclic(4)), g_cyclic(2)))
add("Z8xZ4", g_direct(g_cyclic(8), g_cyclic(4)))
add("Z16xZ2", g_direct(g_cyclic(16), g_cyclic(2)))


# ---------------------------------------------------------------- the S-ring closure
def sring(mul, inv, S):
    """Basic-set partition of the Schur ring generated by S (= the 2-WL closure of
    Cay(G,S), which is translation-invariant hence an S-ring)."""
    n = len(mul)
    part = [0 if x == 0 else (1 if x in S else 2) for x in range(n)]
    while True:
        k = len(set(part))
        rank = {c: i for i, c in enumerate(sorted(set(part)))}
        part = [rank[c] for c in part]
        counts = [[0] * (k * k) for _ in range(n)]
        for t in range(n):
            base = part[t] * k
            row = mul[t]
            for u in range(n):
                counts[row[u]][base + part[u]] += 1
        sig = [(part[g], part[inv[g]], tuple(counts[g])) for g in range(n)]
        newrank = {s: i for i, s in enumerate(sorted(set(sig)))}
        new = [newrank[s] for s in sig]
        if len(set(new)) == len(set(part)):
            return new
        part = new


def cayley_adj(mul, S):
    n = len(mul)
    adj = [[0] * n for _ in range(n)]
    for x in range(n):
        for s in S:
            y = mul[x][s]
            adj[x][y] = adj[y][x] = 1
    return n, adj


def twowl_vertex(n, adj, vcol, cap_rounds=40):
    col = [0] * (n * n)
    init = {}
    for u in range(n):
        for v in range(n):
            k = (0 if u == v else 1, adj[u][v], vcol[u], vcol[v])
            col[u * n + v] = init.setdefault(k, len(init))
    for _ in range(cap_rounds):
        rank, new = {}, [0] * (n * n)
        for u in range(n):
            un = u * n
            for v in range(n):
                s = sorted((col[un + w], col[w * n + v]) for w in range(n))
                key = (col[un + v], tuple(s))
                r = rank.get(key)
                if r is None:
                    r = rank[key] = len(rank)
                new[un + v] = r
        if len(rank) == len(set(col)):
            break
        col = new
    return [col[u * n + u] for u in range(n)]


def connected(mul, S):
    n = len(mul)
    seen = {0}
    fr = [0]
    while fr:
        x = fr.pop()
        for s in S:
            y = mul[x][s]
            if y not in seen:
                seen.add(y)
                fr.append(y)
    return len(seen) == n


# ---------------------------------------------------------------- the sweep
CAP_SETS = 4000


def main():
    say(f"groups: {len(GROUPS)}  (all verified associative, latin, with identity)")
    say("stage 1 = S-ring filter (cheap) | stage 2 = real 2-WL | stage 3 = exact Aut_e")
    say("-" * 100)

    t0 = time.time()
    tot = surv = checked = hits = 0
    skipped_groups = []
    for name, mul in GROUPS:
        n = len(mul)
        inv = [next(y for y in range(n) if mul[x][y] == 0) for x in range(n)]
        classes = []
        seen = set()
        for x in range(1, n):
            if x in seen:
                continue
            c = {x, inv[x]}
            seen |= c
            classes.append(sorted(c))
        nsets = 2 ** len(classes)
        sets = []
        if nsets <= CAP_SETS:
            for mask in range(1, nsets):
                S = frozenset(e for i, c in enumerate(classes) if mask >> i & 1 for e in c)
                sets.append(S)
        else:
            rnd = random.Random(12345)
            seenS = set()
            while len(sets) < CAP_SETS:
                mask = rnd.randrange(1, nsets)
                S = frozenset(e for i, c in enumerate(classes) if mask >> i & 1 for e in c)
                if S not in seenS:
                    seenS.add(S)
                    sets.append(S)
            skipped_groups.append((name, len(classes), nsets, CAP_SETS))
        gsurv = 0
        for S in sets:
            tot += 1
            if not connected(mul, S):
                continue
            p = sring(mul, inv, S)
            szs = defaultdict(int)
            for c in p:
                szs[c] += 1
            if max(szs.values()) == 1:
                continue                                   # S-ring discrete => 2-WL discrete
            surv += 1
            gsurv += 1
            # stage 2: is the S-ring SCHURIAN? (each basic set one Aut_e-orbit)
            # cheap because the automorphism search EXITS EARLY when one exists, which is
            # the common case; only a genuine failure escalates to the real 2-WL run.
            nn, adj = cayley_adj(mul, S)
            root = wl(nn, adj, [0] * nn)
            col1 = individualize(nn, root, 0)
            bs = defaultdict(list)
            for x, c in enumerate(p):
                bs[c].append(x)
            nonschur = False
            for cell in [c for c in bs.values() if len(c) > 1]:
                r = cell[0]
                for v in cell[1:]:
                    if iso_exists(nn, adj, individualize(nn, col1, v),
                                  individualize(nn, col1, r)) is not True:
                        nonschur = True
                        break
                if nonschur:
                    break
            if not nonschur:
                continue                                   # schurian => no counterexample
            checked += 1
            # stage 3: non-schurian S-ring -- does the REAL 2-WL closure split it?
            v2 = twowl_vertex(nn, adj, col1)
            d = defaultdict(list)
            for v, c in enumerate(v2):
                d[c].append(v)
            mixed = []
            for cell in [c for c in d.values() if len(c) > 1]:
                r = cell[0]
                grp = defaultdict(list)
                for v in cell:
                    for q in grp:
                        if iso_exists(nn, adj, individualize(nn, col1, v),
                                      individualize(nn, col1, q)) is True:
                            grp[q].append(v)
                            break
                    else:
                        grp[v] = [v]
                if len(grp) > 1:
                    mixed.append((len(cell), sorted(len(x) for x in grp.values())))
            tag = ""
            if mixed:
                hits += 1
                tag = f"   <<<<<< 2-WL COUNTEREXAMPLE  mixed={mixed}"
            say(f"  {name:10s} n={nn:3d} |S|={len(S):3d} S={sorted(S)}  "
                f"S-ring sizes {sorted(szs.values())}  2-WL cells {sorted(len(c) for c in d.values())}"
                f"{tag}")
        if gsurv:
            say(f"  -- {name}: {gsurv} S-ring-nondiscrete of {len(sets)} sets")

    say("-" * 100)
    say(f"connection sets tried : {tot}")
    say(f"S-ring NON-discrete   : {surv}")
    say(f"S-ring NON-SCHURIAN (the entry ticket) : {checked}")
    say(f"2-WL COUNTEREXAMPLES  : {hits}")
    if skipped_groups:
        say("CAPPED (sampled, not exhaustive):")
        for nm, k, full, cap in skipped_groups:
            say(f"   {nm}: {k} inverse-classes, {full} sets, sampled {cap}")
    say(f"elapsed {time.time() - t0:.0f}s")


if __name__ == "__main__":
    main()
