"""probe_cao_hypercube.py — the reader-proposed Q4 CAO falsifier, measured.

Construction (reader, 2026-08-09):
  * positions = F2^4.  Edge in direction i is replaced by a gadget: a clique on (i+1)
    vertices, every one of them joined to both endpoints  =>  the four directions are
    pairwise distinguishable  =>  Aut of one typed cube = the 16 translations, acting
    REGULARLY (individualize one corner and the whole copy is rigid).
  * 3 copies A,B,C of that; for each position p a CENTRAL vertex m_p joined to A_p,B_p,C_p.
  * CARRIERS: at weight-2 (relative to the base point) the 4-cube has COMPLEMENTARY pairs
    {p, p^1111} inside one distance sphere -- impossible in Q3.  p and p_bar differ in ALL
    four directions, so the pairing is invariant under every direction permutation and
    survives the rigid frame.  For each coset R of V = {0000,1111,0110,1001} (= the four
    positions at distance 2 from the base that the reader's rule keeps), R splits into two
    complementary pairs; a carrier is attached to one corner at each of R's four positions,
    with one copy DOUBLED on one whole pair and the other two copies on the other pair.

The CAO-propagation test (doc chain-descent-cao-propagation.md sec 1):
  start from the EXACT Aut-orbit partition, individualize a central vertex, run 1-WL,
  and compare the cells against the Aut_v-orbits.

Conservative directions used here:
  * the start colouring is the orbit partition of the group generated by the VERIFIED
    generators (translations x copy permutations).  Subgroup orbits are FINER than true
    orbits, so 1-WL is given MORE power than the real test allows: a failure to split here
    is a fortiori a failure to split from the true CAO start.
  * every generator is checked to be an adjacency-preserving bijection before use.
"""

from itertools import product

BITS = [1, 2, 4, 8]            # direction i (0..3) -> bit; gadget size i+1
ALL = 15                       # 1111
COPIES = (0, 1, 2)
VSUB = [0, 15, 6, 9]           # Klein subgroup {0000,1111,0110,1001}


def cosets():
    seen, out = set(), []
    for a in range(16):
        if a in seen:
            continue
        R = sorted(a ^ v for v in VSUB)
        seen.update(R)
        out.append(tuple(R))
    return out


def pairs_of(R):
    a = min(R)
    rest = tuple(sorted(x for x in R if x not in (a, a ^ ALL)))
    assert rest[0] ^ rest[1] == ALL
    return ((a, a ^ ALL), rest)


def patterns(R):
    """12 per coset: doubled copy on one whole complementary pair, other two copies on the other."""
    ps = pairs_of(R)
    for d in (0, 1):
        P, O = ps[d], ps[1 - d]
        for dc in COPIES:
            others = [c for c in COPIES if c != dc]
            for o in (others, others[::-1]):
                yield {P[0]: dc, P[1]: dc, O[0]: o[0], O[1]: o[1]}


def key(phi):
    return ('carr', tuple(sorted(phi.items())))


def build():
    adj = {}

    def add(u, w):
        adj.setdefault(u, set()).add(w)
        adj.setdefault(w, set()).add(u)

    for p in range(16):
        adj.setdefault(('centre', p), set())
        for c in COPIES:
            adj.setdefault(('corner', p, c), set())
            add(('centre', p), ('corner', p, c))

    for p in range(16):
        for i, b in enumerate(BITS):
            q = p ^ b
            if p > q:
                continue
            for c in COPIES:
                mids = [('mid', c, p, q, i, j) for j in range(i + 1)]
                for m in mids:
                    add(m, ('corner', p, c))
                    add(m, ('corner', q, c))
                for a in range(len(mids)):
                    for b2 in range(a + 1, len(mids)):
                        add(mids[a], mids[b2])

    for R in cosets():
        for phi in patterns(R):
            g = key(phi)
            adj.setdefault(g, set())
            for pos, c in phi.items():
                add(g, ('corner', pos, c))
    return adj


def translation(t):
    def f(v):
        if v[0] == 'corner':
            return ('corner', v[1] ^ t, v[2])
        if v[0] == 'centre':
            return ('centre', v[1] ^ t)
        if v[0] == 'mid':
            _, c, p, q, i, j = v
            p2, q2 = p ^ t, q ^ t
            return ('mid', c, min(p2, q2), max(p2, q2), i, j)
        return key({x ^ t: col for x, col in dict(v[1]).items()})
    return f


def copyperm(s):
    def f(v):
        if v[0] == 'corner':
            return ('corner', v[1], s[v[2]])
        if v[0] == 'centre':
            return v
        if v[0] == 'mid':
            return ('mid', s[v[1]], v[2], v[3], v[4], v[5])
        return key({x: s[col] for x, col in dict(v[1]).items()})
    return f


def is_aut(adj, f, name):
    img = {v: f(v) for v in adj}
    assert set(img.values()) == set(adj), f'{name}: not a bijection on V'
    for v, ns in adj.items():
        assert {img[w] for w in ns} == adj[img[v]], f'{name}: adjacency broken at {v}'
    return img


def orbits(adj, maps):
    par = {v: v for v in adj}

    def find(x):
        while par[x] != x:
            par[x] = par[par[x]]
            x = par[x]
        return x

    def uni(a, b):
        ra, rb = find(a), find(b)
        if ra != rb:
            par[ra] = rb

    for img in maps:
        for v in adj:
            uni(v, img[v])
    out = {}
    for v in adj:
        out.setdefault(find(v), []).append(v)
    return out


def wl(adj, colour):
    colour = dict(colour)
    while True:
        sig = {v: (colour[v], tuple(sorted(colour[w] for w in adj[v]))) for v in adj}
        ranked = {s: i for i, s in enumerate(sorted(set(sig.values())))}
        new = {v: ranked[sig[v]] for v in adj}
        if len(set(new.values())) == len(set(colour.values())):
            return colour
        colour = new


def partition(colour, keep=lambda v: True):
    out = {}
    for v, c in colour.items():
        if keep(v):
            out.setdefault(c, []).append(v)
    return out


if __name__ == '__main__':
    adj = build()
    kinds = {}
    for v in adj:
        kinds[v[0]] = kinds.get(v[0], 0) + 1
    print('vertices', len(adj), kinds)

    gens = [(f'trans{b:04b}', translation(b)) for b in BITS]
    gens += [('swapAB', copyperm({0: 1, 1: 0, 2: 2})), ('cycABC', copyperm({0: 1, 1: 2, 2: 0}))]
    maps = [is_aut(adj, f, n) for n, f in gens]
    print('generators verified:', [n for n, _ in gens])

    orb = orbits(adj, maps)
    by_kind = {}
    for cells in orb.values():
        k = cells[0][0]
        by_kind.setdefault(k, []).append(len(cells))
    print('Aut-orbit sizes by kind:', {k: sorted(v) for k, v in by_kind.items()})

    # the reader's two carriers, in bit encoding:
    #   1 = 1100 = dirs{1,2} = 3     1' = 0011 = dirs{3,4} = 12
    #   2 = 1010 = dirs{1,3} = 5     2' = 0101 = dirs{2,4} = 10
    g1 = key({3: 0, 12: 0, 5: 1, 10: 2})     # {A1, A1', B2, C2'}
    g2 = key({3: 1, 12: 2, 5: 0, 10: 0})     # {B1, C1', A2, A2'}
    assert g1 in adj and g2 in adj, 'carriers not in the construction'
    root = {v: i for i, cell in enumerate(orb.values()) for v in cell}
    print('g1, g2 same Aut-orbit at the root:', root[g1] == root[g2])
    t6 = translation(6)                      # 0110, the reader's position 3'
    print('  witness translation 0110 maps g1 -> g2:', t6(g1) == g2,
          '| and moves the base point:', t6(('centre', 0)))

    # TRUE Aut-orbit partition.  centre/corner/carr are each already a SINGLE subgroup orbit,
    # so they are exact.  The only place the subgroup is strictly finer is the gadget middles:
    # the internal clique permutations (which fix every corner, centre and carrier) merge each
    # direction's middles into one orbit.  Merging them by direction gives the exact CAO start.
    def true_cell(v):
        return ('mid', v[4]) if v[0] == 'mid' else (v[0],)

    cells = sorted({true_cell(v) for v in adj})
    start = {v: cells.index(true_cell(v)) for v in adj}
    print('exact CAO start:', {c: sum(1 for v in adj if true_cell(v) == c) for c in cells})
    start[('centre', 0)] = len(cells)
    col = wl(adj, start)

    corner_cells = partition(col, lambda v: v[0] == 'corner')
    carr_cells = partition(col, lambda v: v[0] == 'carr')
    print('after individualizing m_0000: corner cells', sorted(len(c) for c in corner_cells.values()),
          '| carrier cells', sorted(len(c) for c in carr_cells.values()))

    # Aut_{m_0000}: the diagonal copy permutations, PLUS the gadget-internal clique
    # permutations (they fix every corner, centre and carrier, so they are in the
    # stabilizer and must be in the comparison group or the middles report as spurious
    # "mixed" cells).
    kmaps = [is_aut(adj, copyperm(dict(zip(COPIES, s))), 'K') for s in
             [(0, 1, 2), (1, 0, 2), (0, 2, 1), (2, 1, 0), (1, 2, 0), (2, 0, 1)]]

    def swapmid(c, p, q, i, j):
        def f(v):
            if v[0] == 'mid' and v[1:5] == (c, p, q, i) and v[5] in (j, j + 1):
                return ('mid', c, p, q, i, j + 1 if v[5] == j else j)
            return v
        return f

    for p in range(16):
        for i, b in enumerate(BITS):
            q = p ^ b
            if p > q:
                continue
            for c in COPIES:
                for j in range(i):
                    kmaps.append(is_aut(adj, swapmid(c, p, q, i, j), 'Kmid'))
    korb = orbits(adj, kmaps)
    kof = {v: i for i, cell in enumerate(korb.values()) for v in cell}

    mixed = []
    for c, vs in partition(col).items():
        if len({kof[v] for v in vs}) > 1:
            mixed.append((vs[0][0], len(vs), sorted(
                len([v for v in vs if kof[v] == k]) for k in {kof[v] for v in vs})))
    print('MIXED CELLS (1-WL cell strictly coarser than the Aut_v-orbits):', mixed if mixed else 'none')
    print('g1, g2 same 1-WL cell:', col[g1] == col[g2],
          '| same Aut_v-orbit:', kof[g1] == kof[g2])
