#!/usr/bin/env python3
"""
probe_levels.py — DOES COLLECTING THE GUARD'S OWN LEVEL-GENERATORS REPAIR IT?   (2026-08-07)

============================================================================================
THE PROPOSAL BEING TESTED (user, 2026-08-07)
============================================================================================
  > whatever fixed it must be the choice within a cell, so comparing the descents that are
  > generated by those two vertices (which the guard must do anyways) will swap their position

The guard `CertPath` walks each anchor's deepening path and, at EVERY level ψ, requires
`CellIsOrbit deepenSupply adj ψ` — i.e. it already runs a deepen harvest at ψ.  Every generator
that harvest emits is verified `IsColAut adj ψ`, and ψ refines χ, so it is also
`IsColAut adj χ` — a legitimate generator at the ORIGINAL node.  Today they are computed and
thrown away; only the node's own harvest is kept.

So this costs NOTHING beyond the guard's existing (already-unbilled) work.

============================================================================================
THE THREE HARVESTS COMPARED, AT THE RECORDED FALSIFIER
============================================================================================
  A  = node-global, branch-anchored          (today)         — REFUTED: 2 blocks vs 1
  C  = A ∪ every level-generator of every anchor's path       — this proposal
  B  = per-cell: cell c judged by descents on c's own pairs   — the alternative

Reported per cell: block counts on side A-labelling and on its transport, and whether they
agree.  Plus firing counts, since an architecture that is invariant by collapsing nothing is
worthless (standing vacuity trap).

    cd /workspace/scratchpad && python3 -u probe_levels.py > probe_levels.out 2>&1
"""
import random
import sys
from collections import defaultdict

sys.setrecursionlimit(10000)
sys.path.insert(0, '/workspace/scratchpad')

from probe_dualdeepen import circ, MIXED, build_mp, build_cfi_base, cubic
from probe_polyloop import adjlist, refine, indiv, target_cell
from probe_offbranch import deepen_gens, orbits_all, relabel

MAXLEVEL = 60


def cells_of(n, col):
    d = defaultdict(list)
    for v in range(n):
        d[col[v]].append(v)
    return {c: m for c, m in d.items() if len(m) >= 2}


def gens_levels(n, adj, adjl, col):
    """A ∪ { deepen's generators at every level ψ of every anchor's deepening path }.
    Every such generator is IsColAut adj ψ, and ψ refines χ, so it is IsColAut adj χ."""
    cid, C = target_cell(n, col)
    if cid is None:
        return []
    out = list(deepen_gens(n, adj, adjl, col, C))
    for r in sorted(C):
        psi = indiv(n, adjl, col, r)
        for _ in range(MAXLEVEL):
            c2, C2 = target_cell(n, psi)
            if c2 is None:
                break
            out.extend(deepen_gens(n, adj, adjl, psi, C2))
            psi = indiv(n, adjl, psi, min(C2))
    return out


def gens_percell(n, adj, adjl, col, mem):
    return deepen_gens(n, adj, adjl, col, mem)


def blocks(n, gens, mem):
    orb = orbits_all(n, gens)
    return len({orb[v] for v in mem})


def find_falsifier(name, n, adj, depth_members=3, nrel=4):
    """Reproduce probe_offbranch2/3's first off-branch failure: (node χ, σ, cell)."""
    adjl = adjlist(n, adj)
    col0 = refine(n, adjl, [0] * n)
    rng = random.Random(abs(hash(name)) & 0xffff)
    sig = []
    for _ in range(nrel):
        s = list(range(n))
        rng.shuffle(s)
        sig.append(s)
    cid0, C0 = target_cell(n, col0)
    if cid0 is None:
        return None
    cands = [col0] + [indiv(n, adjl, col0, v) for v in sorted(C0)[:depth_members]]
    for col in cands:
        cid, C = target_cell(n, col)
        if cid is None:
            continue
        gA = deepen_gens(n, adj, adjl, col, C)
        for s in sig:
            adj2 = relabel(n, adj, s)
            adjl2 = adjlist(n, adj2)
            col2 = [0] * n
            for w in range(n):
                col2[s[w]] = col[w]
            cid2, C2 = target_cell(n, col2)
            if cid2 is None:
                continue
            gA2 = deepen_gens(n, adj2, adjl2, col2, C2)
            for c, mem in cells_of(n, col).items():
                if c == cid:
                    continue
                mem2 = [s[x] for x in mem]
                if blocks(n, gA, mem) != blocks(n, gA2, mem2):
                    return (col, cid, C, c, mem, s, adj2, adjl2, col2, cid2, C2)
    return None


def run(name, n, adj):
    f = find_falsifier(name, n, adj)
    if f is None:
        print(f"  {name}: no off-branch falsifier reproduced")
        return
    col, cid, C, c, mem, s, adj2, adjl2, col2, cid2, C2 = f
    adjl = adjlist(n, adj)
    mem2 = [s[x] for x in mem]

    gA, gA2 = deepen_gens(n, adj, adjl, col, C), deepen_gens(n, adj2, adjl2, col2, C2)
    gC, gC2 = gens_levels(n, adj, adjl, col), gens_levels(n, adj2, adjl2, col2)
    gB, gB2 = gens_percell(n, adj, adjl, col, mem), gens_percell(n, adj2, adjl2, col2, mem2)

    print(f"  {name}: falsifier at branch colour {cid} (size {len(C)}), "
          f"off-branch colour {c} (size {len(mem)})")
    print(f"      generators emitted:  A={len(gA)}/{len(gA2)}   "
          f"C={len(gC)}/{len(gC2)}   B={len(gB)}/{len(gB2)}")
    for tag, g1, g2 in (('A (today)      ', gA, gA2),
                        ('C (level-gens) ', gC, gC2),
                        ('B (per-cell)   ', gB, gB2)):
        b1, b2 = blocks(n, g1, mem), blocks(n, g2, mem2)
        ok = 'INVARIANT' if b1 == b2 else '<<<< VARIES'
        fires = 'fires' if b1 == 1 else 'stalls'
        print(f"      {tag} blocks {b1} vs {b2}   {ok:11s} ({fires} on side A)")

    # does C repair EVERY cell at this node, not just the one that failed?
    allok = True
    for cc, mm in cells_of(n, col).items():
        mm2 = [s[x] for x in mm]
        if blocks(n, gC, mm) != blocks(n, gC2, mm2):
            allok = False
    print(f"      C across ALL cells of this node: "
          f"{'all invariant' if allok else '<<<< some cell still varies'}")


def main():
    print("Does collecting the guard's own per-level generators repair the falsifier?")
    print("Level-generators are IsColAut adj ψ with ψ refining χ, hence valid at χ, and the")
    print("guard already computes them — so they are free.")
    print()
    base8 = cubic(8, seed=8)
    run("CFI cubic m=8 pl", *build_cfi_base(base8, 8, twist=False))
    run("CFI cubic m=8 tw", *build_cfi_base(base8, 8, twist=True))
    base10 = cubic(10, seed=10)
    run("CFI cubic m=10 pl", *build_cfi_base(base10, 10, twist=False))


if __name__ == '__main__':
    main()
