"""§7.2: would an EQUIVARIANT supply certify the cells along the greedy path?

Proxy for the deck-family (`deckSupply`/`deck2Supply` are the GensEquivariant, propagation-shaped
constructors): seed the pair (u,w), individualize u on one side and w on the other, refine BOTH; if
both leaves are discrete the colour match is forced -- build it and VERIFY with IsColAut.  That is
deepen at ZERO deepening levels, i.e. exactly the depth-0 'linear oracle' the deck supplies model.
It is a LOWER bound on what those supplies certify (they also chain), so a PASS here is decisive
evidence the alternate guard fires; a FAIL is only suggestive."""
import sys; sys.path.insert(0,'/workspace/scratchpad')
import probe_orbit_oracle as P
from collections import defaultdict

def indivOne(col, v, n): return [2*col[u] + (1 if u == v else 0) for u in range(n)]
def step(n, adj, col, v): return P.refine(n, adj, indivOne(col, v, n))

def deck_twist(n, adj, col, u, w):
    """depth-0 forced match: individualize u / w, refine, colour-match, verify."""
    a, b = step(n, adj, col, u), step(n, adj, col, w)
    if len(set(a)) != n or len(set(b)) != n: return None      # not discrete -> no forced match
    pos = {}
    for x in range(n): pos[b[x]] = x
    img = [pos.get(a[x], -1) for x in range(n)]
    if -1 in img or len(set(img)) != n: return None
    return img if P.is_aut(n, adj, img, col) else None

def deck_certifies(n, adj, col, cell):
    """Is the group generated by the depth-0 verified twists transitive on `cell`?"""
    par = {v: v for v in cell}
    def f(x):
        while par[x] != x: par[x] = par[par[x]]; x = par[x]
        return x
    gens = []
    for i, u in enumerate(cell):
        for w in cell[i+1:]:
            t = deck_twist(n, adj, col, u, w)
            if t is not None:
                gens.append(t)
                a, b = f(u), f(w)
                if a != b: par[a] = b
    ch = True
    while ch:
        ch = False
        for g in gens:
            for v in cell:
                if f(v) != f(g[v]): par[f(v)] = f(g[v]); ch = True
    return len({f(v) for v in cell}) == 1

def hook_paths(name, n, adj, maxdepth=2):
    """At every hook node, walk the greedy path from each rep and ask whether the
    equivariant-supply proxy certifies each cell that AmenablePath requires."""
    seen=set(); hooks=0; lv_tot=0; lv_ok=0; full_ok=0
    def amen_vertex_levels(col, v):
        """the cells AmenablePath inspects on v's path (all are single orbits at a hook node)"""
        out=[]; cur=step(n,adj,col,v)
        for _ in range(n+1):
            c2,C2=P.target_cell(n,cur)
            if c2 is None: return out
            out.append((list(cur), C2))
            cur=step(n,adj,cur,min(C2))
        return out
    def rec(col,d):
        nonlocal hooks, lv_tot, lv_ok, full_ok
        k=tuple(col)
        if k in seen or d>maxdepth: return
        seen.add(k)
        cid,C=P.target_cell(n,col)
        if cid is None: return
        tb=P.orbit_partition(n,adj,col,C)
        if tb is None: return
        # hook node = Amenable AND >=2 orbits in the branch cell
        amen=True
        for r in C:
            cur=step(n,adj,col,r)
            for _ in range(n+1):
                c2,C2=P.target_cell(n,cur)
                if c2 is None: break
                op=P.orbit_partition(n,adj,cur,C2)
                if op is None or len(set(op.values()))>1: amen=False; break
                cur=step(n,adj,cur,min(C2))
            if not amen: break
        if amen and len(set(tb.values()))>1:
            hooks+=1; allok=True
            for r in C:
                for (cur,C2) in amen_vertex_levels(col,r):
                    lv_tot+=1
                    if deck_certifies(n,adj,cur,C2): lv_ok+=1
                    else: allok=False
            if allok: full_ok+=1
        for v in C: rec(step(n,adj,col,v),d+1)
    rec(P.refine(n,adj,[0]*n),0)
    pc = (100*lv_ok/lv_tot) if lv_tot else 0.0
    print(f'{name:22s} hooks={hooks:4d}  path-cells={lv_tot:5d}  certified by the '
          f'equivariant proxy={lv_ok:5d} ({pc:5.1f}%)   hook nodes FULLY certified={full_ok}/{hooks}')

print("Would an equivariant (deck-family) supply certify the cells `AmenablePath` inspects?\n")
for nm,g in [('C3+C4', P.disjoint([P.cycle(3),P.cycle(4)])),
             ('C4+C5', P.disjoint([P.cycle(4),P.cycle(5)])),
             ('C3+C4+C5', P.disjoint([P.cycle(3),P.cycle(4),P.cycle(5)])),
             ('Chang-A', P.chang('A')), ('Chang-B', P.chang('B')),
             ('MIXED multipede', P.build_mp(P.MIXED)),
             ('mp7 Fano', P.build_mp(P.FANO))]:
    hook_paths(nm, *g)
